// Regenerates src/data/shortWords.ts from the MIT-licensed
// `an-array-of-english-words` package (dev dependency). Only needed if you
// want to refresh the list; the generated file is committed.
import { writeFileSync } from "node:fs";
import words from "an-array-of-english-words";

const short = (words as string[])
  .filter((w) => w.length >= 2 && w.length <= 4 && /^[a-z]+$/.test(w))
  .map((w) => w.toUpperCase())
  .sort();

const body = `// GENERATED by scripts/build-wordlist.ts - do not edit by hand.
// All 2-4 letter words from "an-array-of-english-words" (MIT licence,
// (c) Zeke Sikelianos). Used to make sure the random letters on the cubes'
// side faces never spell a real word with their neighbours mid-tumble.
export const SHORT_WORDS = ${JSON.stringify(short.join(" "))};
`;
writeFileSync("src/data/shortWords.ts", body);
console.log(`wrote ${short.length} words`);
