/**
 * GENERATED by scripts/generate-ai-chip.mjs — do not edit by hand.
 *
 * Centres of the "Ai" chip's terminal dots, in 0..1 UV space of
 * public/ai-chip.svg (origin top-left). The renderer uses these to pulse the
 * pins in sequence without re-parsing the artwork.
 */
export const AI_CHIP_PINS: readonly (readonly [number, number])[] = [
  [0.29, 0.11],
  [0.41, 0.1],
  [0.45, 0.18],
  [0.5, 0.05],
  [0.55, 0.14],
  [0.59, 0.07],
  [0.72, 0.11],
  [0.86, 0.22],
  [0.89, 0.34],
  [0.89, 0.45],
  [0.83, 0.5],
  [0.93, 0.55],
  [0.85, 0.59],
  [0.94, 0.64],
  [0.71, 0.89],
  [0.59, 0.9],
  [0.55, 0.82],
  [0.5, 0.95],
  [0.45, 0.86],
  [0.41, 0.93],
  [0.28, 0.89],
  [0.14, 0.78],
  [0.11, 0.66],
  [0.11, 0.55],
  [0.17, 0.5],
  [0.07, 0.45],
  [0.15, 0.41],
  [0.06, 0.36],
];
