import React from "react";
import { AbsoluteFill } from "remotion";

const TILE = 240;

// Monochrome fractal noise, generated by the browser from an inline SVG so the
// project carries no binary assets and the tile is rasterised once.
const NOISE_TILE =
  `url("data:image/svg+xml;utf8,` +
  `<svg xmlns='http://www.w3.org/2000/svg' width='${TILE}' height='${TILE}'>` +
  `<filter id='n' x='0' y='0' width='100%25' height='100%25'>` +
  `<feTurbulence type='fractalNoise' baseFrequency='0.8' numOctaves='3' stitchTiles='stitch' seed='7'/>` +
  `<feColorMatrix type='saturate' values='0'/>` +
  `</filter>` +
  `<rect width='${TILE}' height='${TILE}' filter='url(%23n)'/>` +
  `</svg>")`;

/**
 * Fine grain, screened over the finished frame.
 *
 * This is not a texture effect — it is dithering. The falloff into black is a
 * very long, very shallow ramp, and without a per-pixel disturbance H.264 lays
 * visible contour rings across it. A percent or two of noise breaks the
 * quantisation up and the ramp encodes clean.
 */
export const Grain: React.FC<{ strength: number; frame: number }> = ({
  strength,
  frame,
}) => {
  // Shift the tile every frame so the grain reads as film rather than as dirt
  // on the lens. Derived from the frame number only — no accumulated state.
  const ox = (frame * 71) % TILE;
  const oy = (frame * 149) % TILE;

  return (
    <AbsoluteFill
      style={{
        backgroundImage: NOISE_TILE,
        backgroundRepeat: "repeat",
        backgroundPosition: `${ox}px ${oy}px`,
        opacity: strength * 2.2,
        mixBlendMode: "screen",
        pointerEvents: "none",
      }}
    />
  );
};
