// Builds one self-contained, independently runnable project per variant and
// zips it. Each zip carries only its own variant: one entry in VARIANTS, one
// Composition in Root.tsx, and a README describing that composition.
//
//   node scripts/make-zips.mjs
//
// Writes market-dash-<variant>.zip into dist/ .

import { execFileSync } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const staging = join(root, "dist", ".staging");
const dist = join(root, "dist");

const VARIANTS = ["blue", "green", "night"];

const COMPOSITION = {
  blue: "MarketDashBlue",
  green: "MarketDashGreen",
  night: "MarketDashNight",
};

const HEADLINE = {
  blue: "Three dense series over filled continents, 2026 Q1 - 2030 Q4.",
  green:
    "Five series over a dot-matrix map with a sparse bar row, 2015 Q1 - 2025 Q4.",
  night:
    "Two declining series over a coastline wireframe, 2020 Q1 - 2024 Q4.",
};

/**
 * Extracts a single entry from the VARIANTS object literal. The file is
 * generated by hand with one entry per `  <name>: {` ... `  },` block at two
 * spaces of indent, which is what this relies on.
 */
const soleVariant = (source, keep) => {
  const lines = source.split("\n");
  const out = [];
  let skippingKey = null;

  for (const line of lines) {
    const opener = /^ {2}(blue|green|night): \{$/.exec(line);
    if (opener) {
      if (opener[1] !== keep) {
        skippingKey = opener[1];
        continue;
      }
    }
    if (skippingKey) {
      if (line === "  },") skippingKey = null;
      continue;
    }
    out.push(line);
  }

  return out
    .join("\n")
    .replace(
      /export type VariantName = [^;]+;/,
      `export type VariantName = "${keep}";`,
    )
    .replace(/= \{\n\n/g, "= {\n")
    .replace(/\n\n\};/g, "\n};")
    .replace(/\n{3,}/g, "\n\n");
};

const rootTsx = (variant) => `import React from "react";
import { Composition } from "remotion";
import { MarketDash } from "./market-dash/MarketDash";
import {
  DURATION_IN_FRAMES,
  FPS,
  HEIGHT,
  WIDTH,
} from "./market-dash/layout";

export const RemotionRoot: React.FC = () => {
  return (
    <Composition
      id="${COMPOSITION[variant]}"
      component={MarketDash}
      durationInFrames={DURATION_IN_FRAMES}
      fps={FPS}
      width={WIDTH}
      height={HEIGHT}
      defaultProps={{ variant: "${variant}" as const }}
    />
  );
};
`;

const readme = (variant) => `# Market Dash — ${variant}

${HEADLINE[variant]}

A 4K "global market dashboard": polyline series drawn over a low-contrast
world map, a bar row along the bottom and a scrolling quarterly timeline
axis, all advancing on one shared, normalised clock.

## The composition

| | |
| --- | --- |
| Composition id | \`${COMPOSITION[variant]}\` |
| Resolution | **4K — 3840 × 2160** |
| Duration | **420 frames** |
| Frame rate | **30 fps** (14.0 s) |
| Looping | **No.** This is a one-shot. Frames 0 and 420 differ by design — the timeline advances and never resets, so the clip must not be looped or ping-ponged. |

Frames 0–25 hold the dim backdrop and graticule alone, 25–380 advance every
layer together, and 380–420 hold the final state.

## Running it

\`\`\`bash
npm install
npm run dev          # Remotion Studio
\`\`\`

Render at full 4K:

\`\`\`bash
npx remotion render ${COMPOSITION[variant]} out/marketdash-${variant}.mp4 --codec=h264 --crf=12 --concurrency=8
\`\`\`

A faster 1080p preview:

\`\`\`bash
npx remotion render ${COMPOSITION[variant]} out/marketdash-${variant}-preview.mp4 --codec=h264 --crf=18 --scale=0.5 --concurrency=8
\`\`\`

\`--concurrency=8\` assumes at least 8 CPU cores; lower it to your core count
if Remotion rejects the value.

## Map data

\`public/land-110m.json\` is **Natural Earth** 1:110m land, as published in
TopoJSON form by the [world-atlas](https://www.npmjs.com/package/world-atlas)
package.

Natural Earth is **in the public domain**. From its terms of use: "All versions
of Natural Earth raster and vector map data found on this website are in the
public domain. You may use the maps in any manner, including modifying the
content and design, electronic dissemination, and offset printing. The primary
authors, Tom Patterson and Nathaniel Vaughn Kelso, and all other contributors
renounce all financial claim to the mapping and invite you to use it for
personal, educational, and commercial purposes. No permission is needed to use
Natural Earth. Crediting the authors is unnecessary."

No attribution is required, and none is rendered into the frame.

Antarctica is filtered out at load time (any polygon whose northernmost point
sits below 55°S). The geometry is projected once with d3-geo's
\`geoEquirectangular\` into an offscreen canvas and blitted per frame.

## How it is put together

\`src/market-dash/variants.ts\` is the single source of truth: every colour and
every year in the piece lives in the exported \`VARIANTS\` object, and nothing
else in the codebase contains a hex literal or a year.

Everything is drawn to \`<canvas>\` elements through refs, once per React
render. There is no \`requestAnimationFrame\`, no CSS animation, no component
state and no \`Date.now()\` — every value in every frame is a pure function of
\`useCurrentFrame()\`, so frames rendered out of order across workers are
identical to frames rendered in sequence. All randomness comes from Remotion's
\`random()\` with stable string seeds, so the series data is byte-identical on
every render.

The map, the 15° graticule and the axis chrome are rasterised once into
offscreen canvases inside \`useMemo\` and blitted; only the extending lines, the
growing bars and the changing callouts are redrawn per frame.

There are no real company or index names, no watermark and no audio.
`;

const gitignore = "node_modules/\nout/\n.remotion/\n";

rmSync(staging, { recursive: true, force: true });
mkdirSync(dist, { recursive: true });

const variantsSource = readFileSync(
  join(root, "src/market-dash/variants.ts"),
  "utf8",
);
const packageJson = JSON.parse(readFileSync(join(root, "package.json"), "utf8"));

for (const variant of VARIANTS) {
  const project = join(staging, `market-dash-${variant}`);
  mkdirSync(project, { recursive: true });

  for (const entry of ["src", "public", "tsconfig.json", "remotion.config.ts"]) {
    cpSync(join(root, entry), join(project, entry), { recursive: true });
  }

  writeFileSync(
    join(project, "src/market-dash/variants.ts"),
    soleVariant(variantsSource, variant),
  );
  writeFileSync(join(project, "src/Root.tsx"), rootTsx(variant));
  writeFileSync(join(project, "README.md"), readme(variant));
  writeFileSync(join(project, ".gitignore"), gitignore);
  writeFileSync(
    join(project, "package.json"),
    `${JSON.stringify(
      {
        ...packageJson,
        name: `market-dash-${variant}`,
        description: `4K ${variant} global market dashboard animation (Remotion)`,
      },
      null,
      2,
    )}\n`,
  );

  const zip = join(dist, `market-dash-${variant}.zip`);
  if (existsSync(zip)) rmSync(zip);
  execFileSync(
    "zip",
    ["-rq", zip, `market-dash-${variant}`, "-x", "*/node_modules/*", "*/out/*", "*/.git/*"],
    { cwd: staging },
  );
  // eslint-disable-next-line no-console
  console.log(`wrote ${zip}`);
}
