// Converts Natural Earth 1:110m admin-0 country outlines (public domain,
// https://www.naturalearthdata.com/) into src/data/world.ts.
//
// Usage:
//   curl -o ne_110m_admin_0_countries.geojson \
//     https://raw.githubusercontent.com/nvkelso/natural-earth-vector/master/geojson/ne_110m_admin_0_countries.geojson
//   node tools/build-world.mjs ne_110m_admin_0_countries.geojson
//
// Output:
//   WORLD_PATH  - one SVG path, equirectangular, x = lon + 180 (0..360),
//                 y = 90 - lat (0..180). Antarctica is dropped.
//   LAND_MASK   - 360 x 180 grid (1 degree cells), one string per row,
//                 '1' where the cell centre is on land.
// No country names or attributes are kept: geometry only.

import { readFileSync, writeFileSync } from "node:fs";

const src = process.argv[2];
if (!src) {
  console.error("usage: node tools/build-world.mjs <geojson>");
  process.exit(1);
}
const gj = JSON.parse(readFileSync(src, "utf8"));

const polys = []; // array of rings arrays
for (const f of gj.features) {
  if (f.properties.CONTINENT === "Antarctica") continue;
  const g = f.geometry;
  if (g.type === "Polygon") polys.push(g.coordinates);
  else if (g.type === "MultiPolygon") for (const p of g.coordinates) polys.push(p);
}

const r1 = (v) => Math.round(v * 10) / 10;
let d = "";
for (const rings of polys) {
  for (const ring of rings) {
    let prev = "";
    ring.forEach(([lon, lat], i) => {
      const x = r1(lon + 180);
      const y = r1(90 - lat);
      const pt = `${x} ${y}`;
      if (pt === prev) return;
      d += (i === 0 ? "M" : "L") + pt;
      prev = pt;
    });
    d += "Z";
  }
}

const inRing = (x, y, ring) => {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i];
    const [xj, yj] = ring[j];
    if (yi > y !== yj > y && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
};
const onLand = (lon, lat) => {
  for (const rings of polys) {
    if (!inRing(lon, lat, rings[0])) continue;
    let hole = false;
    for (let h = 1; h < rings.length; h++) if (inRing(lon, lat, rings[h])) hole = true;
    if (!hole) return true;
  }
  return false;
};

const rows = [];
for (let r = 0; r < 180; r++) {
  const lat = 89.5 - r;
  let row = "";
  for (let c = 0; c < 360; c++) row += onLand(c - 179.5, lat) ? "1" : "0";
  rows.push(row);
}

const out = `// GENERATED by tools/build-world.mjs from Natural Earth 1:110m
// admin-0 countries (public domain, naturalearthdata.com). Do not edit.
/* eslint-disable */
export const WORLD_PATH = ${JSON.stringify(d)};
export const LAND_MASK: string[] = ${JSON.stringify(rows)};
`;
writeFileSync(new URL("../src/data/world.ts", import.meta.url), out);
console.log(`wrote world.ts: path ${d.length} chars, mask ${rows.length} rows`);
