// Regenerates src/vault/font-data.ts from the woff2 in public/fonts.
// Run with: node scripts/embed-font.mjs
import { readFileSync, writeFileSync } from "node:fs";

const SRC = "public/fonts/Nunito-Bold-latin.woff2";
const OUT = "src/vault/font-data.ts";

const base64 = readFileSync(SRC).toString("base64");

writeFileSync(
  OUT,
  `// Auto-generated by scripts/embed-font.mjs — Nunito 700 (latin subset).
// Embedded as base64 so the composition and the standalone HTML both render
// with the right typeface without a network fetch.
export const NUNITO_BOLD_WOFF2_BASE64 =
  "${base64}";
`,
);

console.log(`Wrote ${OUT} (${base64.length} base64 chars)`);
