// Regenerates the base64 font modules from the woff2 files in public/fonts.
// Run with: node scripts/embed-font.mjs

import { readFileSync, writeFileSync } from "node:fs";

const FONTS = [
  {
    src: "public/fonts/Nunito-Bold-latin.woff2",
    out: "src/vault/font-data.ts",
    constant: "NUNITO_BOLD_WOFF2_BASE64",
    label: "Nunito 700 (latin subset)",
  },
  {
    src: "public/fonts/Caveat-SemiBold-latin.woff2",
    out: "src/pen/font-data.ts",
    constant: "CAVEAT_WOFF2_BASE64",
    label: "Caveat 600 (latin subset)",
  },
];

for (const font of FONTS) {
  const base64 = readFileSync(font.src).toString("base64");
  writeFileSync(
    font.out,
    `// Auto-generated by scripts/embed-font.mjs — ${font.label}.
// Embedded as base64 so the composition and the standalone HTML both render
// with the right typeface without a network fetch.
export const ${font.constant} =
  "${base64}";
`,
  );
  console.log(`Wrote ${font.out} (${base64.length} base64 chars)`);
}
