/**
 * Vendors the shared component library into src/lib/.
 *
 * Remotion bundles from the project root, and each distributable ZIP has to be
 * standalone, so the library is copied in rather than imported across the
 * filesystem. Edit the library at its source, then re-run this and re-render
 * to confirm nothing changed.
 *
 *   node scripts/sync-lib.mjs
 */
import { access, cp, rm, mkdir, writeFile } from "node:fs/promises";
import { homedir } from "node:os";
import path from "node:path";

const exists = async (dir) =>
  access(dir).then(
    () => true,
    () => false,
  );

// $REMOTION_LIB wins; otherwise the working checkout, then the copy that
// travels with this repository.
const candidates = [
  process.env.REMOTION_LIB,
  path.join(homedir(), "projects/remotion-lib"),
  path.join(process.cwd(), "../remotion-lib"),
].filter(Boolean);

let source = null;
for (const candidate of candidates) {
  if (await exists(path.join(candidate, "src"))) {
    source = candidate;
    break;
  }
}
if (!source) {
  throw new Error(
    `Could not find the shared library. Looked in:\n  ${candidates.join("\n  ")}`,
  );
}

const target = path.join(process.cwd(), "src/lib");

await rm(target, { recursive: true, force: true });
await mkdir(target, { recursive: true });
await cp(path.join(source, "src"), target, { recursive: true });
await writeFile(
  path.join(target, "README.md"),
  `# Vendored library\n\nGenerated by \`node scripts/sync-lib.mjs\` from ${source}.\nDo not edit these files here — edit the library and re-sync.\n`,
);
console.log(`Synced ${source}/src -> ${target}`);
