// Generated by tools/bake.mjs — do not edit.
import type {CountryGeo} from '../types';
import unitedStates from './united-states.json';
import china from './china.json';
import india from './india.json';
import iran from './iran.json';
import australia from './australia.json';
import poland from './poland.json';
import italy from './italy.json';
import mexico from './mexico.json';
import sweden from './sweden.json';
import russia from './russia.json';
import japan from './japan.json';
import germany from './germany.json';
import unitedKingdom from './united-kingdom.json';
import france from './france.json';
import brazil from './brazil.json';
import canada from './canada.json';
import indonesia from './indonesia.json';
import turkey from './turkey.json';
import saudiArabia from './saudi-arabia.json';
import southKorea from './south-korea.json';
import spain from './spain.json';
import southAfrica from './south-africa.json';
import netherlands from './netherlands.json';
import uae from './uae.json';
import singapore from './singapore.json';
import vietnam from './vietnam.json';
import nigeria from './nigeria.json';
import egypt from './egypt.json';
import argentina from './argentina.json';
import thailand from './thailand.json';
import philippines from './philippines.json';
import switzerland from './switzerland.json';
import norway from './norway.json';
import chile from './chile.json';

export const GEO: Record<string, CountryGeo> = {
  'united-states': unitedStates,
  'china': china,
  'india': india,
  'iran': iran,
  'australia': australia,
  'poland': poland,
  'italy': italy,
  'mexico': mexico,
  'sweden': sweden,
  'russia': russia,
  'japan': japan,
  'germany': germany,
  'united-kingdom': unitedKingdom,
  'france': france,
  'brazil': brazil,
  'canada': canada,
  'indonesia': indonesia,
  'turkey': turkey,
  'saudi-arabia': saudiArabia,
  'south-korea': southKorea,
  'spain': spain,
  'south-africa': southAfrica,
  'netherlands': netherlands,
  'uae': uae,
  'singapore': singapore,
  'vietnam': vietnam,
  'nigeria': nigeria,
  'egypt': egypt,
  'argentina': argentina,
  'thailand': thailand,
  'philippines': philippines,
  'switzerland': switzerland,
  'norway': norway,
  'chile': chile,
} as unknown as Record<string, CountryGeo>;
