import { between, makeRandom } from "../lib/random";
import { resolveScene, type ConnectorSpec, type NodeSpec } from "../lib/scene";

/**
 * V2 -- violet: right-angle schematic routing between bare bracketed
 * labels and ringed icon badges.
 *
 * Deliberately not V1 with a different palette. The labels lose their
 * capsules, the icon rings carry the accent colour instead of the text,
 * the hero sits inside a rotating dashed circle, and every connector is
 * a horizontal/vertical run with square corners. Swap only the colours
 * and the two versions read as one clip graded twice.
 */
const rng = makeRandom(0x7101e7);

const drift = (tier: number) => ({
  driftCycles: 1 + Math.round(between(rng, 0, 1)),
  driftPhase: rng(),
  driftRadius: between(rng, 10, 26) * (1 + (4 - tier) * 0.2),
});

const label = (
  id: string,
  text: string,
  x: number,
  y: number,
  size: number,
  tier: number,
  extra: Partial<NodeSpec> = {},
): NodeSpec => ({
  id,
  kind: "label",
  shape: "bare",
  x,
  y,
  size,
  tier,
  color: "#eef6ff",
  text,
  ...drift(tier),
  ...extra,
});

const icon = (
  id: string,
  glyph: NodeSpec["glyph"],
  x: number,
  y: number,
  size: number,
  tier: number,
  color: string,
  extra: Partial<NodeSpec> = {},
): NodeSpec => ({
  id,
  kind: "icon",
  shape: "ring",
  x,
  y,
  size,
  tier,
  color,
  glyph,
  ...drift(tier),
  ...extra,
});

const ORANGE = "#e8862a";
const TEAL = "#2fc4d8";

const nodes: NodeSpec[] = [
  // --- Hero, near the centre and the only thing at full brightness.
  {
    id: "hero",
    kind: "hero",
    shape: "ring",
    x: 2575,
    y: 1818,
    size: 1560,
    tier: 0,
    color: "#2ae8fb",
    glow: 0.45,
    layer: 6,
    ...drift(0),
  },

  // --- Sharp bracketed labels.
  label("css", "[CSS]", 2018, 408, 230, 0, { layer: 5 }),
  label("xml", "[XML]", 3946, -198, 280, 0, { layer: 5 }),
  label("sql", "[SQL]", 2255, 2903, 200, 0, { layer: 5 }),
  label("api", "[API]", 5437, 2345, 200, 1, { layer: 3, fade: 0.9 }),

  // --- Icon badges: orange rings and one teal, as in the reference.
  icon("database", "database", 1754, 1027, 320, 1, TEAL, { layer: 3 }),
  icon("globe", "globe", 3454, 1300, 370, 0, ORANGE, { layer: 5 }),
  icon("gears", "gears", 2117, 2620, 290, 1, ORANGE, { layer: 3 }),
  icon("check", "check", 5191, 94, 330, 2, TEAL, { layer: 1, fade: 0.85 }),
  icon("bulb", "bulb", 3100, 640, 260, 1, ORANGE, { layer: 3, fade: 0.9 }),
  label("http2", "[JSON]", 4520, 1980, 210, 1, { layer: 3, fade: 0.85 }),

  // --- Softer mid ground.
  label("php", "[PHP]", 1344, 1484, 250, 2, { layer: 1, fade: 1 }),
  label("seo", "[SEO]", 1382, 2211, 240, 2, { layer: 1, fade: 1 }),
  label("http", "[HTTP]", 5472, 1435, 300, 2, { layer: 1, fade: 0.7 }),

  // --- Out of focus. `layer` puts some behind the network and some in
  // front of the lens; a blur radius on its own cannot say which.
  icon("refresh", "refresh", 554, 2854, 670, 4, ORANGE, { layer: 8, fade: 0.7 }),
  label("json", "[JSON]", 5976, -265, 650, 4, { layer: 8, fade: 0.4 }),
  icon("bolt", "bolt", 502, 868, 550, 3, TEAL, { layer: -3, fade: 0.55 }),
  label("html", "[HTML]", 5124, 2878, 510, 3, { layer: 7, fade: 0.45 }),
  icon("search", "search", 3427, 3007, 430, 3, ORANGE, { layer: -3, fade: 0.5 }),
  label("web", "[WEB]", 1073, 3236, 390, 4, { layer: -4, fade: 0.35 }),
];

/**
 * Right-angle routing. `mode` says which axis the run leaves on -- HVH
 * and VHV turn twice, which is what gives the reference its
 * circuit-schematic feel rather than a plain elbow.
 */
const connectors: ConnectorSpec[] = [
  {
    from: "hero",
    to: "css",
    tier: 0,
    mode: "VHV",
    split: 0.62,
    width: 12,
    dash: 78,
    dashRatio: 0.4,
    march: 27,
    caps: true,
    chevrons: [0.72],
    dots: { count: 1, trips: 2, phase: 0.2 },
    layer: 5.5,
  },
  {
    from: "hero",
    to: "xml",
    tier: 0,
    mode: "HVH",
    split: 0.55,
    width: 12,
    dash: 78,
    dashRatio: 0.4,
    march: 31,
    caps: true,
    dots: { count: 2, trips: 2, phase: 0.6 },
    layer: 5.5,
  },
  {
    from: "hero",
    to: "sql",
    tier: 0,
    mode: "VHV",
    split: 0.55,
    width: 12,
    dash: 78,
    dashRatio: 0.4,
    march: -24,
    caps: true,
    chevrons: [0.3],
    layer: 5.5,
  },
  {
    from: "hero",
    to: "globe",
    tier: 0,
    mode: "HV",
    width: 12,
    dash: 78,
    dashRatio: 0.4,
    march: 19,
    caps: true,
    dots: { count: 1, trips: 3, phase: 0.35 },
    layer: 5.5,
  },
  {
    from: "database",
    to: "css",
    tier: 1,
    mode: "VH",
    width: 11,
    dash: 74,
    dashRatio: 0.4,
    march: 22,
    caps: true,
    layer: 3.5,
  },
  {
    from: "php",
    to: "hero",
    tier: 1,
    mode: "HVH",
    split: 0.48,
    width: 11,
    dash: 74,
    dashRatio: 0.4,
    march: 29,
    caps: true,
    dots: { count: 1, trips: 1, phase: 0.8 },
    layer: 3.5,
  },
  {
    from: "seo",
    to: "hero",
    tier: 1,
    mode: "HVH",
    split: 0.42,
    width: 11,
    dash: 74,
    dashRatio: 0.4,
    march: 26,
    caps: true,
    chevrons: [0.18],
    layer: 3.5,
  },
  {
    from: "gears",
    to: "sql",
    tier: 1,
    mode: "VH",
    width: 11,
    dash: 74,
    dashRatio: 0.4,
    march: -18,
    caps: true,
    layer: 3.5,
  },
  {
    from: "php",
    to: "database",
    tier: 2,
    mode: "VH",
    width: 10,
    dash: 70,
    dashRatio: 0.4,
    march: 16,
    caps: true,
    fade: 0.8,
    layer: 1.5,
  },
  {
    from: "globe",
    to: "api",
    tier: 1,
    mode: "VHV",
    split: 0.5,
    width: 10,
    dash: 70,
    dashRatio: 0.4,
    march: 21,
    caps: true,
    chevrons: [0.62],
    fade: 0.85,
    layer: 3.5,
  },
  {
    from: "xml",
    to: "check",
    tier: 2,
    mode: "HV",
    width: 10,
    dash: 70,
    dashRatio: 0.4,
    march: -14,
    caps: true,
    fade: 0.7,
    layer: 1.5,
  },
  {
    from: "http",
    to: "api",
    tier: 2,
    mode: "VH",
    width: 10,
    dash: 70,
    dashRatio: 0.4,
    march: 17,
    caps: true,
    fade: 0.6,
    layer: 1.5,
  },
  {
    from: "seo",
    to: "web",
    tier: 3,
    mode: "VHV",
    split: 0.5,
    width: 14,
    dash: 92,
    dashRatio: 0.4,
    march: 11,
    fade: 0.45,
    layer: -3.5,
  },
  {
    from: "bolt",
    to: "php",
    tier: 3,
    mode: "VH",
    width: 14,
    dash: 92,
    dashRatio: 0.4,
    march: -9,
    fade: 0.45,
    layer: -3.5,
  },
  {
    from: "database",
    to: "php",
    tier: 1,
    mode: "VHV",
    split: 0.5,
    width: 11,
    dash: 74,
    dashRatio: 0.4,
    march: -20,
    caps: true,
    fade: 0.85,
    layer: 3.5,
  },
  {
    from: "bulb",
    to: "xml",
    tier: 1,
    mode: "VH",
    width: 10,
    dash: 72,
    dashRatio: 0.4,
    march: 23,
    caps: true,
    chevrons: [0.5],
    fade: 0.85,
    layer: 3.5,
  },
  {
    from: "globe",
    to: "http2",
    tier: 1,
    mode: "VH",
    width: 10,
    dash: 72,
    dashRatio: 0.4,
    march: -17,
    caps: true,
    fade: 0.8,
    layer: 3.5,
  },
  {
    from: "gears",
    to: "seo",
    tier: 2,
    mode: "HV",
    width: 10,
    dash: 70,
    dashRatio: 0.4,
    march: 15,
    caps: true,
    fade: 0.75,
    layer: 1.5,
  },
];

export const violetScene = resolveScene({ nodes, connectors, routing: "ortho" });
