/**
 * Generates the neutral studio-gradient environment map used by every look.
 *
 * Why generated rather than downloaded: the reflections show up in look 3's
 * polished floor and in every plinth bevel, so the environment must not contain
 * a recognisable window, softbox or object. A smooth analytic gradient
 * guarantees that, and it is unambiguously licence-free.
 *
 * Output: public/hdri/neutral-studio-gradient.hdr
 *   Radiance RGBE, equirectangular, 1024x512, linear values.
 *
 * Run: node scripts/make-hdri.mjs
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const WIDTH = 1024;
const HEIGHT = 512;

const OUT = resolve(
  dirname(fileURLToPath(import.meta.url)),
  "../public/hdri/neutral-studio-gradient.hdr",
);

const smoothstep = (a, b, x) => {
  const t = Math.min(1, Math.max(0, (x - a) / (b - a)));
  return t * t * (3 - 2 * t);
};

/**
 * Radiance for a direction on the unit sphere.
 *
 * Three broad, soft zones with no hard edges anywhere:
 *  - an overhead dome that acts as the main soft source,
 *  - a neutral horizon band,
 *  - a darker, very slightly warm floor bounce.
 * A wide cosine lobe toward -X/+Z gives materials a gentle directional cue so
 * bevels read, without ever resolving into a recognisable shape.
 */
const sample = (dx, dy, dz) => {
  // Overhead dome: peaks at straight up, falls away smoothly well before the
  // horizon so nothing reads as a rectangular softbox.
  //
  // Deliberately only about twice the horizon's radiance, not four times. An
  // open sky is far brighter overhead than at the horizon, but these are
  // rooms: every look has an upward-facing floor filling the bottom of frame,
  // and a sky-like dome blows it out and erases the shadows falling across
  // it while leaving the vertical surfaces correctly lit.
  const up = Math.max(0, dy);
  const dome = Math.pow(up, 1.35) * 0.85 + smoothstep(-0.15, 0.85, dy) * 0.3;

  // Horizon band: keeps the sides from going flat and gives a wrap highlight.
  const horizon = Math.exp(-Math.pow(dy / 0.34, 2)) * 0.5;

  // Floor bounce: dim, warm-neutral, no detail.
  const down = Math.max(0, -dy);
  const floor = Math.pow(down, 1.2) * 0.14;

  // Very broad key lobe. Normalised direction, cosine falloff, no hard cutoff.
  const kx = -0.45,
    ky = 0.62,
    kz = 0.64;
  const cosKey = Math.max(0, dx * kx + dy * ky + dz * kz);
  const key = Math.pow(cosKey, 3.0) * 1.35;

  // Gentle opposing fill so the shadow side never goes dead.
  const cosFill = Math.max(0, -(dx * kx) + dy * 0.35 - dz * kz * 0.6);
  const fill = Math.pow(Math.max(0, cosFill), 2.5) * 0.3;

  const base = dome + horizon + floor + key + fill + 0.035;

  // A barely-there temperature split: cooler above, warmer below. Keeps it
  // from looking like a synthetic grey ball without tinting the product.
  const warm = smoothstep(0.35, -0.6, dy);
  return [
    base * (1 + warm * 0.055),
    base * (1 + warm * 0.012),
    base * (1 - warm * 0.045),
  ];
};

/** float -> (mantissa, exponent) with 0.5 <= mantissa < 1, as C frexp does. */
const frexp = (value) => {
  if (value === 0 || !Number.isFinite(value)) return [value, 0];
  const absValue = Math.abs(value);
  let exponent = Math.max(-1023, Math.floor(Math.log2(absValue)) + 1);
  let mantissa = absValue * Math.pow(2, -exponent);
  // Guard against log2 rounding pushing the mantissa out of range.
  while (mantissa >= 1) {
    mantissa *= 0.5;
    exponent += 1;
  }
  while (mantissa < 0.5) {
    mantissa *= 2;
    exponent -= 1;
  }
  return [mantissa, exponent];
};

const encodeRgbe = (r, g, b, out, at) => {
  const peak = Math.max(r, g, b);
  if (peak < 1e-32) {
    out[at] = out[at + 1] = out[at + 2] = out[at + 3] = 0;
    return;
  }
  const [mantissa, exponent] = frexp(peak);
  const scale = (mantissa * 256) / peak;
  out[at] = Math.min(255, Math.floor(r * scale));
  out[at + 1] = Math.min(255, Math.floor(g * scale));
  out[at + 2] = Math.min(255, Math.floor(b * scale));
  out[at + 3] = exponent + 128;
};

const pixels = Buffer.alloc(WIDTH * HEIGHT * 4);

for (let y = 0; y < HEIGHT; y++) {
  // Equirectangular: v=0 is straight up (+Y), v=1 is straight down.
  const theta = ((y + 0.5) / HEIGHT) * Math.PI;
  const sinTheta = Math.sin(theta);
  const dy = Math.cos(theta);
  for (let x = 0; x < WIDTH; x++) {
    const phi = ((x + 0.5) / WIDTH) * Math.PI * 2 - Math.PI;
    const dx = sinTheta * Math.sin(phi);
    const dz = sinTheta * Math.cos(phi);
    const [r, g, b] = sample(dx, dy, dz);
    encodeRgbe(r, g, b, pixels, (y * WIDTH + x) * 4);
  }
}

const header = Buffer.from(
  `#?RADIANCE\n# Neutral studio gradient - generated by scripts/make-hdri.mjs\nFORMAT=32-bit_rle_rgbe\n\n-Y ${HEIGHT} +X ${WIDTH}\n`,
  "ascii",
);

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, Buffer.concat([header, pixels]));
console.log(`wrote ${OUT} (${WIDTH}x${HEIGHT}, ${pixels.length + header.length} bytes)`);
