import type { CompositionSpec } from "./types";

/**
 * Everything that varies between the six setups lives here: the layer stack,
 * each layer's tilt and keystone, where the focus band falls, the flare, and
 * the element densities. The renderer only walks this structure — a seventh
 * composition is a new entry, not new code.
 *
 * Layers are listed far-to-near. Neighbouring layers deliberately differ in
 * rotation and keystone: parallel layers read as one flat image with blur
 * applied, differing ones read as separate physical screens.
 */
export const COMPOSITIONS = {
  /* ── t01 · CURVE OVER CANDLES ────────────────────────────────────────
     The curve is the subject and is the only sharp thing in the frame;
     the candles, the red numeric field and the front text are texture. */
  t01: {
    id: "t01",
    focusDepth: 0.5,
    focusBand: 0.09,
    midBand: 0.27,
    bracketBlur: [72, 15, 0, 30, 64],
    bracketBloom: [2.15, 1.25, 1, 1.3, 2.1],
    background: {
      tint: "curvePrimary",
      tintAlpha: 0.16,
      tintX: 0.78,
      tintY: 0.18,
      vignette: 0.34,
      grain: 0.07,
      exposure: 1.12,
    },
    layers: [
      {
        id: "farNumeric",
        depth: 0.93,
        cx: 0.32,
        cy: 0.66,
        w: 1.15,
        h: 0.95,
        rotate: -11,
        keystone: 0.4,
        shear: 0.06,
        glow: 26,
        opacity: 1,
        fade: { from: 1, to: 0.45, angle: 0 },
        content: {
          kind: "numeric",
          fontSize: 210,
          lineHeight: 300,
          columns: 1,
          labelRate: 0.45,
          accentRate: 0.55,
          accent: "candleDown",
          gain: 0.95,
        },
      },
      {
        id: "deepCandles",
        depth: 0.7,
        cx: 0.52,
        cy: 0.52,
        w: 1.25,
        h: 0.8,
        rotate: -7,
        keystone: 0.58,
        shear: 0.03,
        glow: 22,
        opacity: 0.95,
        content: {
          kind: "candles",
          series: "t01market",
          count: 130,
          bodyWidth: 32,
          wickWidth: 6,
          volatility: 1,
          hollowRate: 0.25,
          fill: 0.8,
          gain: 1,
        },
      },
      {
        id: "heroCurve",
        depth: 0.5,
        cx: 0.5,
        cy: 0.48,
        w: 1.3,
        h: 0.78,
        rotate: -3,
        keystone: 0.8,
        shear: 0.01,
        glow: 34,
        opacity: 1,
        content: {
          kind: "curves",
          source: { count: 130, volatility: 1, series: "t01market" },
          fill: 0.8,
          curves: [
            { color: "curvePrimary", window: 65, width: 9, glow: 46, rise: 0.1 },
            {
              color: "curveSecondary",
              window: 150,
              width: 6,
              dash: [46, 30],
              glow: 30,
              offset: 0.07,
              amplitude: 0.8,
            },
          ],
        },
      },
      {
        id: "frontGrid",
        depth: 0.3,
        cx: 0.46,
        cy: 0.5,
        w: 1.4,
        h: 1.1,
        rotate: 5,
        keystone: 1.55,
        shear: -0.04,
        glow: 12,
        opacity: 0.55,
        content: { kind: "grid", pitch: 300, lineWidth: 5, gain: 0.9 },
      },
      {
        id: "frontBinary",
        depth: 0.12,
        cx: 0.3,
        cy: 0.4,
        w: 0.95,
        h: 1.15,
        rotate: 9,
        keystone: 1.95,
        shear: 0.05,
        glow: 20,
        opacity: 0.72,
        fade: { from: 0.25, to: 1, angle: 180 },
        content: {
          kind: "binary",
          fontSize: 260,
          tracking: 0.35,
          lineHeight: 360,
          brightRate: 0.4,
          gain: 1,
        },
      },
      {
        id: "nearDots",
        depth: 0.03,
        cx: 0.84,
        cy: 0.74,
        w: 0.7,
        h: 0.6,
        rotate: -14,
        keystone: 0.42,
        shear: 0.08,
        glow: 18,
        opacity: 0.7,
        content: { kind: "dots", cell: 96, dot: 46, clusters: 4, gain: 1 },
      },
    ],
    flare: {
      x: 0.82,
      y: 0.16,
      core: 0.045,
      halo: 7,
      intensity: 1,
      warmth: -0.7,
      streak: 0.72,
      streakRatio: 0.055,
      streakAlpha: 0.3,
      fringe: 0.05,
      ghosts: 4,
    },
  },

  /* ── t02 · DEPTH OF PANELS ───────────────────────────────────────────
     The most three-dimensional setup: five panels at visibly different
     angles receding to the upper right, with the sharp band on a sparse
     candle series and its node line down in the lower left. */
  t02: {
    id: "t02",
    focusDepth: 0.24,
    focusBand: 0.11,
    midBand: 0.4,
    bracketBlur: [76, 30, 0, 26, 58],
    bracketBloom: [2.2, 1.26, 1, 1.26, 2.1],
    background: {
      tint: "curveSecondary",
      tintAlpha: 0.15,
      tintX: 0.14,
      tintY: 0.86,
      vignette: 0.3,
      grain: 0.07,
      exposure: 1.12,
    },
    layers: [
      {
        id: "panelFar",
        depth: 0.95,
        cx: 0.86,
        cy: 0.16,
        w: 0.78,
        h: 0.58,
        rotate: -22,
        keystone: 0.33,
        shear: 0.1,
        glow: 24,
        opacity: 1,
        content: { kind: "dots", cell: 86, dot: 42, clusters: 3, gain: 1 },
      },
      {
        id: "panelDeep",
        depth: 0.78,
        cx: 0.66,
        cy: 0.3,
        w: 0.82,
        h: 0.62,
        rotate: -13,
        keystone: 0.46,
        shear: 0.05,
        glow: 22,
        opacity: 1,
        content: { kind: "dots", cell: 94, dot: 46, clusters: 4, gain: 1 },
      },
      {
        id: "panelMid",
        depth: 0.6,
        cx: 0.55,
        cy: 0.42,
        w: 1,
        h: 0.75,
        rotate: -5,
        keystone: 0.66,
        shear: 0.02,
        glow: 14,
        opacity: 0.75,
        content: { kind: "grid", pitch: 210, lineWidth: 5, gain: 1 },
      },
      {
        id: "panelNumeric",
        depth: 0.45,
        cx: 0.38,
        cy: 0.62,
        w: 0.9,
        h: 0.7,
        rotate: 11,
        keystone: 1.6,
        shear: -0.05,
        glow: 18,
        opacity: 0.85,
        content: {
          kind: "numeric",
          fontSize: 150,
          lineHeight: 215,
          columns: 1,
          labelRate: 0.5,
          accentRate: 0.45,
          accent: "candleUp",
          gain: 1,
        },
      },
      {
        id: "keyCandles",
        depth: 0.26,
        cx: 0.3,
        cy: 0.7,
        w: 0.85,
        h: 0.55,
        rotate: 3,
        keystone: 0.88,
        shear: 0.01,
        glow: 16,
        opacity: 1,
        content: {
          kind: "candles",
          series: "t02market",
          count: 44,
          bodyWidth: 46,
          wickWidth: 7,
          volatility: 1.2,
          hollowRate: 0.3,
          fill: 0.75,
          gain: 1,
        },
      },
      {
        id: "nodeLine",
        depth: 0.2,
        cx: 0.34,
        cy: 0.66,
        w: 0.95,
        h: 0.6,
        rotate: 2,
        keystone: 0.9,
        shear: 0,
        glow: 26,
        opacity: 1,
        content: {
          kind: "curves",
          source: { count: 44, volatility: 1.2, series: "t02market" },
          fill: 0.75,
          curves: [
            {
              color: "curveSecondary",
              window: 2,
              width: 9,
              glow: 40,
              angular: 18,
              nodes: 20,
            },
            {
              color: "curvePrimary",
              window: 26,
              width: 5,
              dash: [34, 24],
              glow: 24,
              offset: 0.09,
              amplitude: 0.85,
            },
          ],
        },
      },
      {
        id: "frontBinary",
        depth: 0.06,
        cx: 0.7,
        cy: 0.8,
        w: 0.9,
        h: 0.7,
        rotate: 16,
        keystone: 2.0,
        shear: 0.06,
        glow: 20,
        opacity: 0.7,
        fade: { from: 1, to: 0.2, angle: 30 },
        content: {
          kind: "binary",
          fontSize: 250,
          tracking: 0.3,
          lineHeight: 345,
          brightRate: 0.4,
          gain: 1,
        },
      },
    ],
    flare: {
      x: 0.1,
      y: 0.88,
      core: 0.055,
      halo: 8,
      intensity: 1.15,
      warmth: 0.85,
      streak: 0.6,
      streakRatio: 0.06,
      streakAlpha: 0.26,
      fringe: 0.045,
      ghosts: 4,
    },
  },

  /* ── t03 · DENSE CANDLES ─────────────────────────────────────────────
     The busiest setup. A tall, dense, sharp candle series fills the frame
     with a solid and a dashed curve riding over it. */
  t03: {
    id: "t03",
    focusDepth: 0.4,
    focusBand: 0.1,
    midBand: 0.34,
    bracketBlur: [68, 24, 0, 28, 62],
    bracketBloom: [2.15, 1.24, 1, 1.3, 2.1],
    background: {
      tint: "candleUp",
      tintAlpha: 0.13,
      tintX: 0.82,
      tintY: 0.86,
      vignette: 0.3,
      grain: 0.075,
      exposure: 1.12,
    },
    layers: [
      {
        id: "deepBinary",
        depth: 0.92,
        cx: 0.45,
        cy: 0.45,
        w: 1.3,
        h: 1.1,
        rotate: -12,
        keystone: 0.44,
        shear: 0.07,
        glow: 26,
        opacity: 1,
        content: {
          kind: "binary",
          fontSize: 270,
          tracking: 0.32,
          lineHeight: 375,
          brightRate: 0.4,
          gain: 1,
        },
      },
      {
        id: "deepGrid",
        depth: 0.72,
        cx: 0.52,
        cy: 0.5,
        w: 1.35,
        h: 1,
        rotate: -6,
        keystone: 0.62,
        shear: 0.03,
        glow: 12,
        opacity: 0.75,
        content: { kind: "grid", pitch: 250, lineWidth: 5, gain: 1 },
      },
      {
        id: "deepNumeric",
        depth: 0.56,
        cx: 0.64,
        cy: 0.36,
        w: 1,
        h: 0.8,
        rotate: -9,
        keystone: 0.54,
        shear: 0.04,
        glow: 20,
        opacity: 0.95,
        content: {
          kind: "numeric",
          fontSize: 110,
          lineHeight: 160,
          columns: 2,
          labelRate: 0.4,
          accentRate: 0.3,
          accent: "curveSecondary",
          gain: 1,
        },
      },
      {
        id: "mainCandles",
        depth: 0.4,
        cx: 0.5,
        cy: 0.5,
        w: 1.32,
        h: 0.92,
        rotate: -2.5,
        keystone: 0.86,
        shear: 0.01,
        glow: 20,
        opacity: 1,
        content: {
          kind: "candles",
          series: "t03market",
          count: 230,
          bodyWidth: 22,
          wickWidth: 4,
          volatility: 1,
          hollowRate: 0.2,
          fill: 0.88,
          gain: 1,
        },
      },
      {
        id: "overCurves",
        depth: 0.33,
        cx: 0.5,
        cy: 0.48,
        w: 1.32,
        h: 0.88,
        rotate: -1,
        keystone: 0.88,
        shear: 0,
        glow: 20,
        opacity: 1,
        content: {
          kind: "curves",
          source: { count: 230, volatility: 1, series: "t03market" },
          fill: 0.88,
          curves: [
            { color: "candleUp", window: 30, width: 8, glow: 18 },
            {
              color: "curveSecondary",
              window: 85,
              width: 6,
              dash: [40, 26],
              glow: 32,
              offset: -0.06,
            },
          ],
        },
      },
      {
        id: "frontDots",
        depth: 0.14,
        cx: 0.22,
        cy: 0.72,
        w: 0.7,
        h: 0.6,
        rotate: 8,
        keystone: 1.7,
        shear: -0.05,
        glow: 16,
        opacity: 0.7,
        content: { kind: "dots", cell: 92, dot: 44, clusters: 3, gain: 1 },
      },
      {
        id: "frontBinary",
        depth: 0.03,
        cx: 0.8,
        cy: 0.3,
        w: 0.85,
        h: 1,
        rotate: 13,
        keystone: 1.95,
        shear: 0.05,
        glow: 22,
        opacity: 0.65,
        content: {
          kind: "binary",
          fontSize: 255,
          tracking: 0.34,
          lineHeight: 350,
          brightRate: 0.4,
          gain: 1,
        },
      },
    ],
    flare: {
      x: 0.86,
      y: 0.82,
      core: 0.042,
      halo: 7,
      intensity: 0.9,
      warmth: 0.8,
      streak: 0.66,
      streakRatio: 0.05,
      streakAlpha: 0.26,
      fringe: 0.045,
      ghosts: 3,
    },
  },

  /* ── t04 · SOFT AND DARK ─────────────────────────────────────────────
     The sharp band sits on a numeric field, so the candles behind it stay
     soft. Underexposed on purpose: this is the one meant to carry text. */
  t04: {
    id: "t04",
    focusDepth: 0.42,
    focusBand: 0.09,
    midBand: 0.32,
    bracketBlur: [42, 18, 0, 30, 70],
    bracketBloom: [1.95, 1.16, 1, 1.22, 1.95],
    background: {
      tint: "curvePrimary",
      tintAlpha: 0.11,
      tintX: 0.5,
      tintY: 0.95,
      vignette: 0.42,
      grain: 0.08,
      exposure: 0.94,
    },
    layers: [
      {
        id: "softCandles",
        depth: 0.9,
        cx: 0.56,
        cy: 0.5,
        w: 1.35,
        h: 0.95,
        rotate: -8,
        keystone: 0.5,
        shear: 0.05,
        glow: 14,
        opacity: 0.85,
        content: {
          kind: "candles",
          series: "t04market",
          count: 26,
          bodyWidth: 150,
          wickWidth: 26,
          volatility: 1,
          hollowRate: 0.3,
          fill: 0.8,
          gain: 0.95,
        },
      },
      {
        id: "paleCurve",
        depth: 0.72,
        cx: 0.5,
        cy: 0.5,
        w: 1.35,
        h: 0.9,
        rotate: -4,
        keystone: 0.72,
        shear: 0.02,
        glow: 10,
        opacity: 0.8,
        content: {
          kind: "curves",
          source: { count: 26, volatility: 1, series: "t04market" },
          fill: 0.62,
          curves: [
            { color: "textBright", window: 24, width: 7, glow: 12, rise: 0.22 },
          ],
        },
      },
      {
        id: "midGrid",
        depth: 0.58,
        cx: 0.55,
        cy: 0.52,
        w: 1.3,
        h: 1,
        rotate: 3,
        keystone: 1.42,
        shear: -0.03,
        glow: 10,
        opacity: 0.5,
        content: { kind: "grid", pitch: 160, lineWidth: 4, gain: 1 },
      },
      {
        id: "focusNumeric",
        depth: 0.42,
        cx: 0.38,
        cy: 0.44,
        w: 0.86,
        h: 0.74,
        rotate: -1.5,
        keystone: 0.9,
        shear: 0.01,
        glow: 16,
        opacity: 0.8,
        fade: { from: 1, to: 0.12, angle: 25 },
        content: {
          kind: "numeric",
          fontSize: 34,
          lineHeight: 50,
          columns: 2,
          labelRate: 0.55,
          accentRate: 0.26,
          accent: "candleUp",
          gain: 1,
        },
      },
      {
        id: "dotsLowerRight",
        depth: 0.24,
        cx: 0.78,
        cy: 0.78,
        w: 0.62,
        h: 0.5,
        rotate: 10,
        keystone: 1.65,
        shear: -0.05,
        glow: 14,
        opacity: 0.9,
        content: { kind: "dots", cell: 56, dot: 27, clusters: 3, gain: 1 },
      },
      {
        id: "softBinaryFront",
        depth: 0.05,
        cx: 0.2,
        cy: 0.3,
        w: 0.8,
        h: 0.9,
        rotate: -13,
        keystone: 0.45,
        shear: 0.06,
        glow: 22,
        opacity: 0.5,
        content: {
          kind: "binary",
          fontSize: 250,
          tracking: 0.35,
          lineHeight: 345,
          brightRate: 0.4,
          gain: 1,
        },
      },
    ],
    flare: {
      x: 0.46,
      y: 0.9,
      core: 0.028,
      halo: 6,
      intensity: 0.7,
      warmth: -0.8,
      streak: 0.42,
      streakRatio: 0.05,
      streakAlpha: 0.2,
      fringe: 0.03,
      ghosts: 3,
    },
  },

  /* ── t05 · WARM CROSSING ─────────────────────────────────────────────
     Two temperatures in one frame. The candle stack and the dashed curve
     are pushed cool, the sharp hero curve is pushed warm, and the flare
     bleeds in warm from the upper right. */
  t05: {
    id: "t05",
    focusDepth: 0.4,
    focusBand: 0.09,
    midBand: 0.32,
    bracketBlur: [60, 26, 0, 30, 64],
    bracketBloom: [2.2, 1.25, 1, 1.28, 2.15],
    background: {
      tint: "curveSecondary",
      tintAlpha: 0.13,
      tintX: 0.12,
      tintY: 0.72,
      vignette: 0.24,
      grain: 0.07,
      exposure: 1.3,
    },
    layers: [
      {
        id: "binaryTopLeft",
        depth: 0.92,
        cx: 0.16,
        cy: 0.22,
        w: 0.85,
        h: 0.75,
        rotate: -16,
        keystone: 0.4,
        shear: 0.06,
        glow: 12,
        opacity: 0.45,
        warmth: -0.8,
        content: {
          kind: "binary",
          fontSize: 255,
          tracking: 0.34,
          lineHeight: 350,
          brightRate: 0.4,
          gain: 1,
        },
      },
      {
        id: "binaryTopRight",
        depth: 0.84,
        cx: 0.84,
        cy: 0.2,
        w: 0.82,
        h: 0.72,
        rotate: 14,
        keystone: 2.1,
        shear: -0.05,
        glow: 12,
        opacity: 0.45,
        warmth: -0.8,
        content: {
          kind: "binary",
          fontSize: 255,
          tracking: 0.34,
          lineHeight: 350,
          brightRate: 0.4,
          gain: 1,
        },
      },
      {
        id: "coolCandles",
        depth: 0.7,
        cx: 0.5,
        cy: 0.54,
        w: 1.3,
        h: 0.95,
        rotate: -6,
        keystone: 0.66,
        shear: 0.03,
        glow: 6,
        opacity: 1,
        warmth: -0.35,
        content: {
          kind: "candles",
          series: "t05market",
          count: 78,
          bodyWidth: 58,
          wickWidth: 10,
          volatility: 1.05,
          hollowRate: 0.22,
          fill: 0.8,
          gain: 1,
        },
      },
      {
        id: "dashedUnder",
        depth: 0.52,
        cx: 0.5,
        cy: 0.58,
        w: 1.3,
        h: 0.8,
        rotate: -4,
        keystone: 0.78,
        shear: 0.02,
        glow: 26,
        opacity: 1,
        warmth: -0.8,
        content: {
          kind: "curves",
          source: { count: 78, volatility: 1.05, series: "t05market" },
          fill: 0.8,
          curves: [
            {
              color: "curveSecondary",
              window: 26,
              width: 8,
              dash: [64, 40],
              glow: 34,
              offset: 0.14,
            },
          ],
        },
      },
      {
        id: "warmCurve",
        depth: 0.4,
        cx: 0.5,
        cy: 0.48,
        w: 1.35,
        h: 0.8,
        rotate: -2,
        keystone: 0.88,
        shear: 0,
        glow: 38,
        opacity: 1,
        warmth: 0.85,
        content: {
          kind: "curves",
          source: { count: 78, volatility: 1.05, series: "t05market" },
          fill: 0.8,
          curves: [
            { color: "curvePrimary", window: 55, width: 9, glow: 50, rise: 0.2 },
          ],
        },
      },
      {
        id: "frontGrid",
        depth: 0.18,
        cx: 0.48,
        cy: 0.5,
        w: 1.4,
        h: 1.1,
        rotate: 7,
        keystone: 1.6,
        shear: -0.04,
        glow: 10,
        opacity: 0.28,
        warmth: -0.8,
        content: { kind: "grid", pitch: 290, lineWidth: 5, gain: 1 },
      },
      {
        id: "frontNumeric",
        depth: 0.04,
        cx: 0.7,
        cy: 0.82,
        w: 0.9,
        h: 0.6,
        rotate: -11,
        keystone: 0.44,
        shear: 0.05,
        glow: 20,
        opacity: 0.45,
        warmth: -0.7,
        content: {
          kind: "numeric",
          fontSize: 215,
          lineHeight: 300,
          columns: 1,
          labelRate: 0.4,
          accentRate: 0.45,
          accent: "candleDown",
          gain: 1,
        },
      },
    ],
    flare: {
      x: 0.93,
      y: 0.1,
      core: 0.05,
      halo: 6.5,
      intensity: 0.85,
      warmth: 0.95,
      streak: 1.05,
      streakRatio: 0.06,
      streakAlpha: 0.3,
      fringe: 0.06,
      ghosts: 4,
    },
  },

  /* ── t06 · CODE AND CHARTS ───────────────────────────────────────────
     The only setup where code is the subject: a steeply tilted block down
     the left third holds the focus, with the charts soft on the right. */
  t06: {
    id: "t06",
    focusDepth: 0.3,
    focusBand: 0.09,
    midBand: 0.28,
    bracketBlur: [72, 28, 0, 26, 60],
    bracketBloom: [2.6, 1.55, 1, 1.5, 2.5],
    background: {
      tint: "curveSecondary",
      tintAlpha: 0.13,
      tintX: 0.97,
      tintY: 0.5,
      vignette: 0.34,
      grain: 0.07,
      exposure: 1.12,
    },
    layers: [
      {
        id: "deepDots",
        depth: 0.9,
        cx: 0.62,
        cy: 0.32,
        w: 1,
        h: 0.8,
        rotate: -14,
        keystone: 0.42,
        shear: 0.07,
        glow: 24,
        opacity: 0.4,
        content: { kind: "dots", cell: 90, dot: 44, clusters: 4, gain: 1 },
      },
      {
        id: "rightNumeric",
        depth: 0.72,
        cx: 0.8,
        cy: 0.7,
        w: 0.8,
        h: 0.7,
        rotate: 9,
        keystone: 1.75,
        shear: -0.05,
        glow: 20,
        opacity: 0.9,
        content: {
          kind: "numeric",
          fontSize: 115,
          lineHeight: 168,
          columns: 2,
          labelRate: 0.45,
          accentRate: 0.25,
          accent: "candleDown",
          gain: 1,
        },
      },
      {
        id: "rightCandles",
        depth: 0.56,
        cx: 0.72,
        cy: 0.54,
        w: 0.95,
        h: 0.78,
        rotate: -5,
        keystone: 0.68,
        shear: 0.03,
        glow: 12,
        opacity: 1,
        content: {
          kind: "candles",
          series: "t06market",
          count: 60,
          bodyWidth: 48,
          wickWidth: 8,
          volatility: 1,
          hollowRate: 0.24,
          fill: 0.8,
          gain: 1,
        },
      },
      {
        id: "rightCurves",
        depth: 0.44,
        cx: 0.72,
        cy: 0.52,
        w: 0.95,
        h: 0.74,
        rotate: -3,
        keystone: 0.78,
        shear: 0.02,
        glow: 18,
        opacity: 0.9,
        content: {
          kind: "curves",
          source: { count: 60, volatility: 1, series: "t06market" },
          fill: 0.8,
          curves: [
            { color: "curvePrimary", window: 34, width: 7, glow: 24 },
            {
              color: "curveSecondary",
              window: 80,
              width: 5,
              dash: [40, 26],
              glow: 26,
              offset: -0.06,
            },
          ],
        },
      },
      {
        id: "codeLeft",
        depth: 0.3,
        cx: 0.2,
        cy: 0.5,
        w: 0.44,
        h: 1.05,
        rotate: -13,
        keystone: 0.46,
        shear: 0.09,
        glow: 18,
        opacity: 1,
        content: { kind: "code", fontSize: 46, lineHeight: 70, gain: 1 },
      },
      {
        id: "frontBinary",
        depth: 0,
        cx: 0.5,
        cy: 0.85,
        w: 1.2,
        h: 0.5,
        rotate: 5,
        keystone: 1.5,
        shear: -0.03,
        glow: 20,
        opacity: 0.35,
        content: {
          kind: "binary",
          fontSize: 235,
          tracking: 0.33,
          lineHeight: 325,
          brightRate: 0.4,
          gain: 1,
        },
      },
      {
        id: "frontGridSoft",
        depth: 0.02,
        cx: 0.5,
        cy: 0.5,
        w: 1.5,
        h: 1.2,
        rotate: 11,
        keystone: 1.8,
        shear: -0.06,
        glow: 10,
        opacity: 0.42,
        content: { kind: "grid", pitch: 330, lineWidth: 6, gain: 1 },
      },
    ],
    flare: {
      x: 1.02,
      y: 0.46,
      core: 0.07,
      halo: 9,
      intensity: 1.15,
      warmth: 0.85,
      streak: 0.8,
      streakRatio: 0.055,
      streakAlpha: 0.28,
      fringe: 0.05,
      ghosts: 4,
    },
  },
} as const satisfies Record<string, CompositionSpec>;

export type CompositionName = keyof typeof COMPOSITIONS;

export const COMPOSITION_NAMES = Object.keys(COMPOSITIONS) as CompositionName[];

export const isCompositionName = (v: string): v is CompositionName =>
  Object.prototype.hasOwnProperty.call(COMPOSITIONS, v);
