/**
 * The look data rows.
 *
 * Everything that distinguishes one composition from another lives here.
 * Adding a look means adding a row: branch parameters, palette, pulse style,
 * background and blur. No component below this file needs to change.
 */

import type { Look } from "./types";

export const FPS = 30;
export const DURATION_IN_FRAMES = 600;
export const WIDTH = 3840;
export const HEIGHT = 2160;

type DeepPartial<T> = {
  [K in keyof T]?: T[K] extends object
    ? T[K] extends readonly unknown[]
      ? T[K]
      : DeepPartial<T[K]>
    : T[K];
};

/** A mid-range network neuron. Each row overrides what it needs. */
const BASE: Omit<Look, "id" | "file" | "seed" | "stillFrames"> = {
  field: {
    neuronCount: 8,
    hero: false,
    heroRadius: 1.25,
    heroCenter: [-1.2, 0.5, 2.0],
    radius: 0.42,
    spreadX: 1.0,
    spreadY: 1.0,
    zNear: 1.5,
    zFar: -14,
    backgroundDepthDrop: 3,
  },
  grow: {
    primariesMin: 5,
    primariesMax: 7,
    branchProbability: 0.3,
    maxDepth: 7,
    lengthDecay: 0.82,
    minRadiusFraction: 0.05,
    baseRadius: 0.055,
    baseLength: 0.42,
    maxSegmentsPerBranch: 5,
    wanderAngle: 0.3,
    branchAngle: 0.55,
    segmentTaper: 0.93,
    radiusExponent: 2.5,
    outwardBias: 0.32,
    maxBranches: 340,
    somaRadius: 0.42,
    tipRadius: 0.08,
    tipTaperPower: 1.25,
  },
  soma: {
    detail: 4,
    displacement: 0.09,
    frequency: 5,
    octaves: 4,
    faceted: false,
  },
  tube: {
    radialCap: 9,
    subdivisions: 3,
    myelinAmplitude: 0,
    myelinPeriod: 0.3,
    myelinFraction: 0,
    transparent: false,
    minAlpha: 1,
    ambient: 0.22,
    rimStrength: 0.45,
    rimPower: 2.4,
    somaBleed: 0.4,
    somaBleedFalloff: 4.5,
  },
  palette: {
    bgInner: "#0a1936",
    bgOuter: "#01030a",
    tube: "#5f86bd",
    rim: "#a8cdf5",
    somaCore: "#eaf4ff",
    somaGlow: "#4f93d8",
    pulse: "#bfe4ff",
    node: "#7fd8ff",
    particle: "#cfe8ff",
  },
  emissive: { soma: 1.3, somaRim: 0.45, corePower: 4.0 },
  pulse: {
    slots: 1,
    counts: [2],
    amplitude: 0.8,
    sigma: 0.045,
    hardness: 0,
    junctionFlare: 0,
    cellPulseCycles: 0,
    cellPulseDepth: 0,
    flashCycles: 0,
    flashStrength: 0,
    nodeStrength: 0,
    nodeGate: [0.08, 0.35],
  },
  particles: {
    count: 0,
    size: 8,
    brightness: 1,
    alongFibres: false,
    spread: 0.5,
    amplitude: 0.25,
  },
  sparks: { count: 0, size: 26, strength: 0, cycles: 4 },
  camera: {
    position: [0, 0, 9],
    target: [0, 0, 0],
    fov: 42,
    amplitude: [0.55, 0.35, 0.3],
    frequency: [1, 1, 1],
    phase: [0, 0.25, 0.5],
    near: 0.5,
    far: 45,
  },
  post: {
    focusWorld: 10.0,
    focusRangeWorld: 5.0,
    bokehScale: 8,
    bloomIntensity: 1.1,
    bloomThreshold: 0.72,
    bloomSmoothing: 0.22,
    grain: 0.019,
    exposure: 1,
    crf: 16,
    bgLift: 0.3,
    bgGain: 1,
    multisampling: 4,
  },
};

const merge = (over: DeepPartial<Omit<Look, "id" | "file" | "seed" | "stillFrames">>) => {
  const out = structuredClone(BASE) as Omit<Look, "id" | "file" | "seed" | "stillFrames">;
  for (const key of Object.keys(over) as (keyof typeof out)[]) {
    Object.assign(out[key] as object, over[key] as object);
  }
  return out;
};

export const LOOKS: Look[] = [
  // ---------------------------------------------------------------- Look 1A
  // One dominant soma, grainy and matted. The whole cell brightens and fades
  // exactly twice across the loop; no travelling pulse.
  {
    id: "HeroNeuronMatted",
    file: "HeroNeuron_Matted",
    seed: 10101,
    stillFrames: [75, 225, 450],
    ...merge({
      field: {
        neuronCount: 20,
        hero: true,
        heroRadius: 1.35,
        heroCenter: [-1.9, 0.6, 2.0],
        radius: 0.42,
        spreadX: 1.1,
        spreadY: 1.1,
        zNear: -3,
        zFar: -20,
        backgroundDepthDrop: 4,
      },
      grow: {
        segmentTaper: 0.85,
        primariesMin: 6,
        primariesMax: 8,
        branchProbability: 0.4,
        maxDepth: 9,
        lengthDecay: 0.85,
        baseRadius: 0.2,
        baseLength: 0.62,
        minRadiusFraction: 0.045,
        maxBranches: 1500,
        tipRadius: 0.06,
        tipTaperPower: 1.3,
        maxSegmentsPerBranch: 4,
        somaRadius: 1.35,
        wanderAngle: 0.34,
        branchAngle: 0.62,
      },
      soma: { detail: 5, displacement: 0.1, frequency: 7, octaves: 5 },
      tube: { radialCap: 10, subdivisions: 3, ambient: 0.42, rimStrength: 0.6, somaBleed: 0.55, somaBleedFalloff: 4.0 },
      palette: {
        bgInner: "#0b1e3f",
        bgOuter: "#04101f",
        tube: "#14528f",
        rim: "#9fdcff",
        somaCore: "#8ec8ff",
        somaGlow: "#4b8ed4",
        node: "#38f0ff",
        particle: "#bfe0ff",
      },
      emissive: { soma: 0.8, somaRim: 1.5, corePower: 8.0 },
      pulse: { slots: 0, cellPulseCycles: 2, cellPulseDepth: 0.85, nodeStrength: 1.8, nodeGate: [0.05, 0.3] },
      camera: { position: [0, 0, 9.5], fov: 42, amplitude: [0.22, 0.14, 0.12] },
      post: {
        focusWorld: 7.0,
        focusRangeWorld: 3.6,
        bokehScale: 10,
        bloomIntensity: 1.15,
        bloomThreshold: 0.95,
        bgLift: 0.35,
      },
    }),
  },

  // ---------------------------------------------------------------- Look 1B
  // The same framing read as ice: faceted, cooler, steady. Star-like specks.
  {
    id: "HeroNeuronCrystalline",
    file: "HeroNeuron_Crystalline",
    seed: 20202,
    stillFrames: [40, 280, 520],
    ...merge({
      field: {
        neuronCount: 14,
        hero: true,
        heroRadius: 1.55,
        heroCenter: [1.9, -0.5, 2.6],
        radius: 0.45,
        spreadX: 1.15,
        spreadY: 1.15,
        zNear: -2.5,
        zFar: -20,
        backgroundDepthDrop: 4,
      },
      grow: {
        segmentTaper: 0.86,
        primariesMin: 6,
        primariesMax: 8,
        branchProbability: 0.3,
        maxDepth: 9,
        lengthDecay: 0.86,
        baseRadius: 0.21,
        baseLength: 0.68,
        minRadiusFraction: 0.05,
        maxBranches: 1300,
        tipRadius: 0.07,
        tipTaperPower: 1.3,
        somaRadius: 1.55,
        wanderAngle: 0.22,
      },
      // Low subdivision plus flat shading is what makes the crystal read.
      soma: { detail: 4, displacement: 0.2, frequency: 3.2, octaves: 2, faceted: true },
      tube: { radialCap: 10, subdivisions: 3, ambient: 0.44, rimStrength: 0.75, somaBleed: 0.5, somaBleedFalloff: 4.5, rimPower: 2.0 },
      palette: {
        bgInner: "#0c2352",
        bgOuter: "#05142c",
        tube: "#2f66c0",
        rim: "#d8ecff",
        somaCore: "#b6e6ff",
        somaGlow: "#2f9ae8",
        node: "#a7e8ff",
        particle: "#e8f6ff",
      },
      emissive: { soma: 0.95, somaRim: 1.6, corePower: 6.0 },
      pulse: { slots: 0, nodeStrength: 0.9, nodeGate: [0.05, 0.3] },
      particles: { count: 420, size: 5, brightness: 1.5, spread: 0.4, amplitude: 0.18 },
      camera: { position: [0, 0, 13.5], fov: 42, amplitude: [0.25, 0.16, 0.14] },
      post: {
        focusWorld: 10.9,
        focusRangeWorld: 4.2,
        bokehScale: 9,
        bloomIntensity: 1.25,
        bloomThreshold: 0.92,
        bgLift: 0.4,
      },
    }),
  },

  // ---------------------------------------------------------------- Look 2A
  // Teal somas with hot white cores against warm grey-pink dendrites. The
  // contrast between cool glow and warm branch is the identity here.
  {
    id: "NetworkDriftTeal",
    file: "NetworkDrift_Teal",
    seed: 30303,
    stillFrames: [110, 300, 470],
    ...merge({
      field: { neuronCount: 8,
        hero: true,
        heroRadius: 0.62,
        heroCenter: [-1.6, 0.1, 3.4], radius: 0.4, spreadX: 1.0, spreadY: 1.0, zNear: 1, zFar: -15 },
      grow: {
        primariesMin: 5,
        primariesMax: 7,
        branchProbability: 0.26,
        maxDepth: 8,
        lengthDecay: 0.86,
        baseRadius: 0.052,
        baseLength: 0.44,
        maxBranches: 420,
        tipRadius: 0.05,
        tipTaperPower: 1.2,
        somaRadius: 0.4,
      },
      soma: { displacement: 0.07, frequency: 5 },
      tube: { radialCap: 8, subdivisions: 3, ambient: 0.3, rimStrength: 0.35, somaBleed: 0.65, somaBleedFalloff: 5.5, rimPower: 2.6 },
      palette: {
        bgInner: "#17282f",
        bgOuter: "#0c1319",
        tube: "#7d6a68",
        rim: "#cbb3aa",
        somaCore: "#ffffff",
        somaGlow: "#1fd4cd",
        pulse: "#9ff7f2",
        node: "#3ce6dd",
        particle: "#eafcff",
      },
      emissive: { soma: 1.5, somaRim: 1.3, corePower: 10.0 },
      pulse: { slots: 1, counts: [1, 2], amplitude: 0.55, sigma: 0.05 },
      particles: { count: 170, size: 5.5, brightness: 1.3, spread: 0.6, amplitude: 0.35 },
      camera: { position: [0, 0, 9], fov: 40, amplitude: [0.7, 0.45, 0.4] },
      post: {
        focusWorld: 12.0,
        focusRangeWorld: 6.0,
        bokehScale: 9,
        bloomIntensity: 1.2,
        bloomThreshold: 0.7,
        bgLift: 0.25,
      },
    }),
  },

  // ---------------------------------------------------------------- Look 2B
  // Deep navy and deliberately smooth. Sparser, with long sweeping dendrites
  // that cross the whole frame, and a few orange specks riding them.
  {
    id: "NetworkDriftNavy",
    file: "NetworkDrift_Navy",
    seed: 40404,
    stillFrames: [60, 260, 500],
    ...merge({
      field: { neuronCount: 5, radius: 0.5, spreadX: 1.0, spreadY: 1.0, zNear: 1.5, zFar: -15 },
      grow: {
        segmentTaper: 0.95,
        primariesMin: 5,
        primariesMax: 7,
        branchProbability: 0.2,
        maxDepth: 6,
        lengthDecay: 0.9,
        baseRadius: 0.075,
        baseLength: 0.8,
        maxSegmentsPerBranch: 7,
        wanderAngle: 0.16,
        outwardBias: 0.42,
        maxBranches: 320,
        tipRadius: 0.11,
        tipTaperPower: 1.5,
        somaRadius: 0.5,
      },
      // Smooth: no surface texture at all, per the reference.
      soma: { detail: 4, displacement: 0.03, frequency: 3, octaves: 2 },
      tube: { radialCap: 10, subdivisions: 4, ambient: 0.3, rimStrength: 0.8, somaBleed: 0.28, somaBleedFalloff: 6.0, rimPower: 2.2 },
      palette: {
        bgInner: "#0b1b4d",
        bgOuter: "#01030f",
        tube: "#1c3f8c",
        rim: "#8fc0ff",
        somaCore: "#cfe2ff",
        somaGlow: "#2b6fd0",
        pulse: "#ff8a2e",
        node: "#ffa64d",
        particle: "#ff9a3c",
      },
      emissive: { soma: 0.8, somaRim: 0.6, corePower: 6.0 },
      pulse: { slots: 1, counts: [1], amplitude: 0.9, sigma: 0.02, hardness: 0.65 },
      particles: { count: 90, size: 6, brightness: 1.4, spread: 0.5, amplitude: 0.3 },
      camera: { position: [0, 0, 8.5], fov: 44, amplitude: [0.6, 0.4, 0.45] },
      post: {
        focusWorld: 12.0,
        focusRangeWorld: 7.0,
        bokehScale: 10,
        bloomIntensity: 1.0,
        bloomThreshold: 0.75,
        bgLift: 0.3,
      },
    }),
  },

  // ---------------------------------------------------------------- Look 3A
  // The pulse is the subject: warm gold travelling along blue dendrites and
  // flaring as it crosses a junction. Myelin collars along some branches.
  {
    id: "PulseNetworkGold",
    file: "PulseNetwork_Gold",
    seed: 50505,
    stillFrames: [95, 290, 455],
    ...merge({
      field: { neuronCount: 14, radius: 0.44, spreadX: 1.0, spreadY: 1.0, zNear: 1.8, zFar: -14 },
      grow: {
        primariesMin: 6,
        primariesMax: 8,
        branchProbability: 0.35,
        maxDepth: 8,
        lengthDecay: 0.8,
        baseRadius: 0.06,
        baseLength: 0.46,
        maxBranches: 620,
        tipRadius: 0.06,
        tipTaperPower: 1.25,
        somaRadius: 0.44,
      },
      soma: { displacement: 0.08 },
      tube: {
        radialCap: 8,
        subdivisions: 3,
        myelinAmplitude: 0.7,
        myelinPeriod: 0.22,
        myelinFraction: 0.55,
        ambient: 0.38,
        rimStrength: 0.62,
        somaBleed: 0.4,
        somaBleedFalloff: 5.0,
      },
      palette: {
        bgInner: "#2a1220",
        bgOuter: "#0a0407",
        tube: "#4a7fd0",
        rim: "#9ec8ff",
        somaCore: "#dbe8ff",
        somaGlow: "#5b7fd8",
        pulse: "#ffb63c",
        node: "#ffd489",
        particle: "#ffc98a",
      },
      emissive: { soma: 1.0, somaRim: 0.4, corePower: 5.0 },
      pulse: {
        slots: 2,
        counts: [1, 2],
        amplitude: 0.62,
        sigma: 0.075,
        hardness: 0,
        junctionFlare: 1.6,
      },
      particles: { count: 260, size: 7, brightness: 1.2, alongFibres: true, spread: 0.4, amplitude: 0.2 },
      camera: { position: [0, 0, 8.6], fov: 42, amplitude: [0.6, 0.4, 0.4] },
      post: {
        focusWorld: 11.0,
        focusRangeWorld: 6.0,
        bokehScale: 10,
        bloomIntensity: 1.05,
        bloomThreshold: 0.88,
        bgLift: 0.3,
      },
    }),
  },

  // ---------------------------------------------------------------- Look 3B
  // Magenta dashes: short, hard-edged, many at once, at visibly different
  // speeds because each dendrite draws its traversal count from 1, 2 or 3.
  {
    id: "PulseNetworkMagenta",
    file: "PulseNetwork_Magenta",
    seed: 60606,
    stillFrames: [70, 310, 480],
    ...merge({
      field: { neuronCount: 9,
        hero: true,
        heroRadius: 0.6,
        heroCenter: [0.9, -1.3, 1.6], radius: 0.42, spreadX: 0.95, spreadY: 0.95, zNear: 3.2, zFar: -13 },
      grow: {
        primariesMin: 6,
        primariesMax: 8,
        branchProbability: 0.32,
        maxDepth: 9,
        lengthDecay: 0.82,
        baseRadius: 0.125,
        baseLength: 0.6,
        maxBranches: 520,
        tipRadius: 0.05,
        tipTaperPower: 1.15,
        somaRadius: 0.42,
      },
      soma: { displacement: 0.06, frequency: 8, octaves: 4 },
      tube: { radialCap: 10, subdivisions: 3, ambient: 0.4, rimStrength: 0.55, somaBleed: 0.55, somaBleedFalloff: 4.5, rimPower: 3.0 },
      palette: {
        bgInner: "#081444",
        bgOuter: "#030820",
        tube: "#1740d8",
        rim: "#89c0ff",
        somaCore: "#ff2ea8",
        somaGlow: "#8e0f5e",
        pulse: "#ff1e8c",
        node: "#ff87c2",
        particle: "#ff9ccd",
      },
      emissive: { soma: 0.7, somaRim: 1.4, corePower: 5.0 },
      pulse: {
        slots: 3,
        counts: [1, 2, 3],
        amplitude: 1.6,
        sigma: 0.006,
        hardness: 1,
        junctionFlare: 0.6,
      },
      camera: { position: [0, 0, 7.5], fov: 46, amplitude: [0.5, 0.35, 0.5] },
      post: {
        focusWorld: 8.0,
        focusRangeWorld: 3.0,
        bokehScale: 11,
        bloomIntensity: 1.6,
        bloomThreshold: 0.7,
        bgLift: 0.25,
      },
    }),
  },

  // ----------------------------------------------------------------- Look 4
  // Inverted: the background is a violet glow LIGHTER than the structure, so
  // the dendrites read as dark silhouettes. Star-shaped sparks at junctions.
  {
    id: "DenseMeshViolet",
    file: "DenseMesh_Violet",
    seed: 70707,
    stillFrames: [55, 275, 495],
    ...merge({
      field: {
        neuronCount: 46,
        radius: 0.24,
        spreadX: 1.15,
        spreadY: 1.15,
        zNear: 3,
        zFar: -16,
        backgroundDepthDrop: 2,
      },
      grow: {
        segmentTaper: 0.92,
        primariesMin: 7,
        primariesMax: 9,
        branchProbability: 0.45,
        maxDepth: 10,
        lengthDecay: 0.78,
        baseRadius: 0.035,
        baseLength: 0.42,
        minRadiusFraction: 0.05,
        maxBranches: 1100,
        tipRadius: 0.045,
        tipTaperPower: 1.1,
        somaRadius: 0.3,
      },
      soma: { detail: 3, displacement: 0.1 },
      tube: { radialCap: 5, subdivisions: 2, ambient: 0.02, rimStrength: 0.08, rimPower: 3.5, somaBleed: 0.0, somaBleedFalloff: 6.0 },
      palette: {
        // Light violet field, dark structure. Building this dark-on-light by
        // habit is what destroys the look, so the inversion is explicit.
        bgInner: "#c6b5f5",
        bgOuter: "#231a55",
        tube: "#0b0518",
        rim: "#6d5ba8",
        somaCore: "#2a1f45",
        somaGlow: "#3a2c5e",
        pulse: "#ffffff",
        node: "#ffd8ff",
        particle: "#ffd8ff",
      },
      emissive: { soma: 0.4, somaRim: 0.12, corePower: 2.0 },
      pulse: {
        slots: 0,
        flashCycles: 5,
        flashStrength: 2.6, nodeGate: [0.03, 0.2],
        nodeStrength: 0,
      },
      sparks: { count: 420, size: 34, strength: 2.4, cycles: 5 },
      camera: { position: [0, 0, 8], fov: 52, amplitude: [0.85, 0.6, 0.55] },
      post: {
        focusWorld: 11.0,
        focusRangeWorld: 5.0,
        bokehScale: 9,
        bloomIntensity: 1.5,
        bloomThreshold: 0.86,
        grain: 0.016,
        bgLift: 1.0,
        multisampling: 8,
      },
    }),
  },

  {
    id: "DenseMeshTeal",
    file: "DenseMesh_Teal",
    seed: 70808,
    stillFrames: [95, 255, 470],
    ...merge({
      field: {
        neuronCount: 46,
        radius: 0.24,
        spreadX: 1.15,
        spreadY: 1.15,
        zNear: 3,
        zFar: -16,
        backgroundDepthDrop: 2,
      },
      grow: {
        segmentTaper: 0.92,
        primariesMin: 7,
        primariesMax: 9,
        branchProbability: 0.45,
        maxDepth: 10,
        lengthDecay: 0.78,
        baseRadius: 0.035,
        baseLength: 0.42,
        minRadiusFraction: 0.05,
        maxBranches: 1100,
        tipRadius: 0.045,
        tipTaperPower: 1.1,
        somaRadius: 0.3,
      },
      soma: { detail: 3, displacement: 0.1 },
      tube: { radialCap: 5, subdivisions: 2, ambient: 0.02, rimStrength: 0.08, rimPower: 3.5, somaBleed: 0.0, somaBleedFalloff: 6.0 },
      palette: {
        bgInner: "#aeecf2",
        bgOuter: "#0e3a42",
        tube: "#03151a",
        rim: "#3f7f88",
        somaCore: "#15343a",
        somaGlow: "#1d454c",
        pulse: "#ffffff",
        node: "#eafffe",
        particle: "#ffffff",
      },
      emissive: { soma: 0.4, somaRim: 0.12, corePower: 2.0 },
      pulse: { slots: 0, flashCycles: 5, flashStrength: 2.6, nodeGate: [0.03, 0.2], nodeStrength: 0 },
      sparks: { count: 420, size: 34, strength: 2.4, cycles: 5 },
      camera: { position: [0, 0, 8], fov: 52, amplitude: [0.85, 0.6, 0.55] },
      post: {
        focusWorld: 11.0,
        focusRangeWorld: 5.0,
        bokehScale: 9,
        bloomIntensity: 1.5,
        bloomThreshold: 0.86,
        grain: 0.016,
        bgLift: 1.0,
        multisampling: 8,
      },
    }),
  },

  // ----------------------------------------------------------------- Look 5
  // Near-white, clear and glass-like, with localised glowing nodes. The one
  // worth over-weighting: the rest of this market is dark blue.
  {
    id: "ClearLightGold",
    file: "ClearLight_Gold",
    seed: 80808,
    stillFrames: [45, 265, 505],
    ...merge({
      field: {
        neuronCount: 6,
        hero: true,
        heroRadius: 0.8,
        heroCenter: [-0.55, 0.2, 1.4],
        radius: 0.45,
        spreadX: 1.0,
        spreadY: 1.0,
        zNear: -4,
        zFar: -11,
        backgroundDepthDrop: 2,
      },
      grow: {
        segmentTaper: 0.94,
        primariesMin: 9,
        primariesMax: 11,
        branchProbability: 0.36,
        maxDepth: 8,
        lengthDecay: 0.88,
        baseRadius: 0.042,
        baseLength: 0.72,
        minRadiusFraction: 0.07,
        maxSegmentsPerBranch: 6,
        wanderAngle: 0.2,
        outwardBias: 0.38,
        maxBranches: 1600,
        tipRadius: 0.045,
        tipTaperPower: 1.2,
        somaRadius: 0.8,
      },
      soma: { detail: 4, displacement: 0.02, frequency: 3, octaves: 2 },
      tube: {
        radialCap: 8,
        subdivisions: 3,
        transparent: true,
        minAlpha: 0.5,
        ambient: 0.34,
        rimStrength: 1.35,
        somaBleed: 0.9,
        somaBleedFalloff: 3.2,
        rimPower: 1.8,
      },
      palette: {
        bgInner: "#f2f5fa",
        bgOuter: "#c3cfe0",
        tube: "#b9c4d2",
        rim: "#ffffff",
        somaCore: "#fff3d2",
        somaGlow: "#ffc863",
        pulse: "#ffd68a",
        node: "#ffc250",
        particle: "#fff0cc",
      },
      emissive: { soma: 6.0, somaRim: 0.4, corePower: 4.5 },
      pulse: { slots: 0, nodeStrength: 7.0, nodeGate: [0.015, 0.1] },
      camera: { position: [0, 0, 10.5], fov: 42, amplitude: [0.3, 0.2, 0.2] },
      post: {
        focusWorld: 9.1,
        focusRangeWorld: 6.0,
        bokehScale: 4,
        bloomIntensity: 2.1,
        bloomThreshold: 4.4,
        bloomSmoothing: 0.3,
        grain: 0.02,
        crf: 8,
        bgLift: 0.15,
        bgGain: 4.2,
      },
    }),
  },

  // 5B differs from 5A in node colour only.
  {
    id: "ClearLightCool",
    file: "ClearLight_Cool",
    seed: 80808,
    stillFrames: [45, 265, 505],
    ...merge({
      field: {
        neuronCount: 6,
        hero: true,
        heroRadius: 0.8,
        heroCenter: [-0.55, 0.2, 1.4],
        radius: 0.45,
        spreadX: 1.0,
        spreadY: 1.0,
        zNear: -4,
        zFar: -11,
        backgroundDepthDrop: 2,
      },
      grow: {
        segmentTaper: 0.94,
        primariesMin: 9,
        primariesMax: 11,
        branchProbability: 0.36,
        maxDepth: 8,
        lengthDecay: 0.88,
        baseRadius: 0.042,
        baseLength: 0.72,
        minRadiusFraction: 0.07,
        maxSegmentsPerBranch: 6,
        wanderAngle: 0.2,
        outwardBias: 0.38,
        maxBranches: 1600,
        tipRadius: 0.045,
        tipTaperPower: 1.2,
        somaRadius: 0.8,
      },
      soma: { detail: 4, displacement: 0.02, frequency: 3, octaves: 2 },
      tube: {
        radialCap: 8,
        subdivisions: 3,
        transparent: true,
        minAlpha: 0.5,
        ambient: 0.34,
        rimStrength: 1.35,
        somaBleed: 0.9,
        somaBleedFalloff: 3.2,
        rimPower: 1.8,
      },
      palette: {
        bgInner: "#f2f5fa",
        bgOuter: "#c3cfe0",
        tube: "#b9c4d2",
        rim: "#ffffff",
        somaCore: "#eaf6ff",
        somaGlow: "#7fc4ff",
        pulse: "#bfe4ff",
        node: "#5fb4ff",
        particle: "#dcf0ff",
      },
      emissive: { soma: 6.0, somaRim: 0.4, corePower: 4.5 },
      pulse: { slots: 0, nodeStrength: 7.0, nodeGate: [0.015, 0.1] },
      camera: { position: [0, 0, 10.5], fov: 42, amplitude: [0.3, 0.2, 0.2] },
      post: {
        focusWorld: 9.1,
        focusRangeWorld: 6.0,
        bokehScale: 4,
        bloomIntensity: 2.1,
        bloomThreshold: 4.4,
        bloomSmoothing: 0.3,
        grain: 0.02,
        crf: 8,
        bgLift: 0.15,
        bgGain: 4.2,
      },
    }),
  },

  // ----------------------------------------------------------------- Look 6
  // Fluorescence microscopy rather than a render: far more terminals, much
  // finer radii, high branching probability, short length decay. Pure black.
  {
    id: "FibrousFieldBlue",
    file: "FibrousField_Blue",
    seed: 90909,
    stillFrames: [80, 300, 520],
    ...merge({
      field: {
        neuronCount: 11,
        hero: true,
        heroRadius: 0.42,
        heroCenter: [-0.5, 0.1, 1.2],
        radius: 0.26,
        spreadX: 1.12,
        spreadY: 1.12,
        zNear: 2.5,
        zFar: -8,
        backgroundDepthDrop: 2,
      },
      grow: {
        segmentTaper: 0.9,
        primariesMin: 8,
        primariesMax: 10,
        branchProbability: 0.6,
        maxDepth: 12,
        lengthDecay: 0.78,
        baseRadius: 0.032,
        baseLength: 0.34,
        minRadiusFraction: 0.012,
        maxSegmentsPerBranch: 4,
        wanderAngle: 0.62,
        branchAngle: 0.88,
        outwardBias: 0.3,
        maxBranches: 3100,
        tipRadius: 0.035,
        tipTaperPower: 1.0,
        somaRadius: 0.34,
      },
      soma: { detail: 3, displacement: 0.14, frequency: 6, octaves: 4 },
      tube: { radialCap: 4, subdivisions: 2, ambient: 0.45, rimStrength: 0.7, somaBleed: 0.5, somaBleedFalloff: 3.5, rimPower: 2.2 },
      palette: {
        // Pure black, verified on the encoded file rather than the preview.
        bgInner: "#02070f",
        bgOuter: "#000000",
        tube: "#2f9ae8",
        rim: "#9fe4ff",
        somaCore: "#86c6f5",
        somaGlow: "#2f7fc8",
        pulse: "#bfe4ff",
        node: "#7fc8ff",
        particle: "#ffa53c",
      },
      emissive: { soma: 0.45, somaRim: 0.5, corePower: 4.0 },
      pulse: { slots: 0, nodeStrength: 0 },
      particles: {
        count: 90,
        size: 3.4,
        brightness: 1.3,
        alongFibres: true,
        spread: 0.22,
        amplitude: 0.12,
      },
      camera: { position: [0, 0, 6.5], fov: 44, amplitude: [0.8, 0.55, 0.5] },
      post: {
        // Extreme: most of the frame soft, a thin band sharp.
        focusWorld: 7.0,
        focusRangeWorld: 2.6,
        bokehScale: 10,
        bloomIntensity: 1.3,
        bloomThreshold: 0.72,
        grain: 0.016,
        bgLift: 0.55,
        multisampling: 8,
      },
    }),
  },
];

export const LOOK_BY_ID = new Map(LOOKS.map((l) => [l.id, l]));
