/**
 * Grain.tsx — the only 2D layer in the piece.
 *
 * Fine film grain at ~4% over the finished canvas. The noise is generated by
 * an SVG feTurbulence whose `seed` is the Remotion frame, so it changes every
 * frame but is identical on every render.
 *
 * Rendered at half resolution and scaled up: feTurbulence at 3840x2160 is
 * genuinely slow, and the visual difference at 4% opacity is nil.
 */

import React from 'react';
import {AbsoluteFill, useCurrentFrame, useVideoConfig} from 'remotion';

export const Grain: React.FC<{opacity: number}> = ({opacity}) => {
	const frame = useCurrentFrame();
	const {width, height} = useVideoConfig();
	const w = Math.ceil(width / 2);
	const h = Math.ceil(height / 2);
	const id = `wire-city-grain-${frame}`;

	return (
		<AbsoluteFill
			style={{
				opacity,
				mixBlendMode: 'overlay',
				pointerEvents: 'none',
			}}
		>
			<svg
				width={w}
				height={h}
				viewBox={`0 0 ${w} ${h}`}
				style={{
					transform: 'scale(2)',
					transformOrigin: 'top left',
					display: 'block',
				}}
			>
				<filter id={id} x="0" y="0" width="100%" height="100%">
					<feTurbulence
						type="fractalNoise"
						baseFrequency="0.85"
						numOctaves={1}
						seed={frame}
						stitchTiles="stitch"
					/>
					<feColorMatrix type="saturate" values="0" />
				</filter>
				<rect width={w} height={h} filter={`url(#${id})`} />
			</svg>
		</AbsoluteFill>
	);
};
