// GENERATED by scripts/build-assets.ts — do not edit.
import type {Region} from '../regionTypes';

import ARE from './regions/ARE.json';
import ARG from './regions/ARG.json';
import AUS from './regions/AUS.json';
import BRA from './regions/BRA.json';
import CAN from './regions/CAN.json';
import CHE from './regions/CHE.json';
import CHL from './regions/CHL.json';
import CHN from './regions/CHN.json';
import DEU from './regions/DEU.json';
import EGY from './regions/EGY.json';
import ESP from './regions/ESP.json';
import FRA from './regions/FRA.json';
import GBR from './regions/GBR.json';
import IDN from './regions/IDN.json';
import IND from './regions/IND.json';
import ITA from './regions/ITA.json';
import JPN from './regions/JPN.json';
import KOR from './regions/KOR.json';
import MEX from './regions/MEX.json';
import NGA from './regions/NGA.json';
import NLD from './regions/NLD.json';
import NOR from './regions/NOR.json';
import PHL from './regions/PHL.json';
import POL from './regions/POL.json';
import RUS from './regions/RUS.json';
import SAU from './regions/SAU.json';
import SGP from './regions/SGP.json';
import SWE from './regions/SWE.json';
import THA from './regions/THA.json';
import TUR from './regions/TUR.json';
import USA from './regions/USA.json';
import VNM from './regions/VNM.json';
import ZAF from './regions/ZAF.json';

export const REGIONS = {
  ARE: ARE as unknown as Region,
  ARG: ARG as unknown as Region,
  AUS: AUS as unknown as Region,
  BRA: BRA as unknown as Region,
  CAN: CAN as unknown as Region,
  CHE: CHE as unknown as Region,
  CHL: CHL as unknown as Region,
  CHN: CHN as unknown as Region,
  DEU: DEU as unknown as Region,
  EGY: EGY as unknown as Region,
  ESP: ESP as unknown as Region,
  FRA: FRA as unknown as Region,
  GBR: GBR as unknown as Region,
  IDN: IDN as unknown as Region,
  IND: IND as unknown as Region,
  ITA: ITA as unknown as Region,
  JPN: JPN as unknown as Region,
  KOR: KOR as unknown as Region,
  MEX: MEX as unknown as Region,
  NGA: NGA as unknown as Region,
  NLD: NLD as unknown as Region,
  NOR: NOR as unknown as Region,
  PHL: PHL as unknown as Region,
  POL: POL as unknown as Region,
  RUS: RUS as unknown as Region,
  SAU: SAU as unknown as Region,
  SGP: SGP as unknown as Region,
  SWE: SWE as unknown as Region,
  THA: THA as unknown as Region,
  TUR: TUR as unknown as Region,
  USA: USA as unknown as Region,
  VNM: VNM as unknown as Region,
  ZAF: ZAF as unknown as Region,
} as const satisfies Record<string, Region>;

export type RegionCode = keyof typeof REGIONS;

export const hasRegion = (code: string): code is RegionCode =>
  Object.prototype.hasOwnProperty.call(REGIONS, code);
