import type { MarkSpec } from "../types";

/**
 * V2 "dense" — centred cluster.
 *
 * The same vocabulary and the same construction as v1, but the distribution is
 * inverted: marks pack around frame centre on a tighter 85px pitch and are
 * allowed to overlap and layer, while the edges are left empty. Three marks —
 * and only three — carry the accent colour.
 *
 * Arrival is three distinct waves with pauses between them: the largest marks
 * first, then mid-sized ones filling in around them, then the small detail.
 * Everything then clears at once over twenty frames.
 */
export const DENSE_FIELD: MarkSpec[] = [
  // ── wave one, frames 15-45: the largest marks ─────────────────────────────
  {
    id: "d-x",
    type: "crossedX",
    gx: 22,
    gy: 12,
    wc: 6,
    hc: 6,
    rot: 0,
    tone: "ink",
    in: 15,
    inDur: 5,
    out: 230,
    outDur: 20,
    spin: 1,
  },
  {
    id: "d-circ",
    type: "circleOutline",
    gx: 21,
    gy: 12,
    wc: 12,
    hc: 12,
    rot: 0,
    tone: "dim",
    in: 18,
    inDur: 5,
    out: 230,
    outDur: 20,
    spin: -0.6,
  },
  {
    id: "d-panel1",
    type: "squarePanel",
    gx: 16,
    gy: 8,
    wc: 4,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 21,
    inDur: 5,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-panel2",
    type: "squarePanel",
    gx: 28,
    gy: 15,
    wc: 4,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 24,
    inDur: 5,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-brk1",
    type: "cornerBracket",
    gx: 14,
    gy: 6,
    wc: 3,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 27,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-brk2",
    type: "cornerBracket",
    gx: 30,
    gy: 6,
    wc: 3,
    hc: 3,
    rot: 90,
    tone: "ink",
    in: 30,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-brk3",
    type: "cornerBracket",
    gx: 30,
    gy: 18,
    wc: 3,
    hc: 3,
    rot: 180,
    tone: "ink",
    in: 33,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-brk4",
    type: "cornerBracket",
    gx: 14,
    gy: 18,
    wc: 3,
    hc: 3,
    rot: 270,
    tone: "ink",
    in: 36,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-arc1",
    type: "arc",
    gx: 18,
    gy: 15,
    wc: 8,
    hc: 8,
    rot: 0,
    tone: "dim",
    in: 39,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { start: 20, sweep: 110 },
  },
  {
    id: "d-arc2",
    type: "arc",
    gx: 26,
    gy: 9,
    wc: 8,
    hc: 8,
    rot: 0,
    tone: "dim",
    in: 42,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { start: 200, sweep: 100 },
  },

  // ── wave two, frames 60-95: mid-sized marks fill in around them ──────────
  {
    id: "d-tick1",
    type: "tickRow",
    gx: 18,
    gy: 5,
    wc: 4,
    hc: 0.6,
    rot: 0,
    tone: "ink",
    in: 60,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { ticks: 12 },
  },
  {
    id: "d-tick2",
    type: "tickRow",
    gx: 26,
    gy: 19,
    wc: 4,
    hc: 0.6,
    rot: 0,
    tone: "ink",
    in: 62,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { ticks: 12 },
  },
  {
    id: "d-tick3",
    type: "tickRow",
    gx: 16,
    gy: 13,
    wc: 3,
    hc: 0.5,
    rot: 0,
    tone: "dim",
    in: 64,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { ticks: 9 },
  },
  {
    id: "d-tick4",
    type: "tickRow",
    gx: 28,
    gy: 11,
    wc: 3,
    hc: 0.5,
    rot: 0,
    tone: "ink",
    in: 66,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { ticks: 9 },
  },
  {
    id: "d-dot1",
    type: "dotColumn",
    gx: 13,
    gy: 10,
    wc: 1,
    hc: 4,
    rot: 0,
    tone: "ink",
    in: 68,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { columns: 2, dots: 9 },
  },
  {
    id: "d-dot2",
    type: "dotColumn",
    gx: 31,
    gy: 13,
    wc: 1,
    hc: 4,
    rot: 0,
    tone: "ink",
    in: 70,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { columns: 2, dots: 9 },
  },
  {
    id: "d-dot3",
    type: "dotColumn",
    gx: 19,
    gy: 17,
    wc: 0.6,
    hc: 3,
    rot: 0,
    tone: "dim",
    in: 72,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { dots: 7 },
  },
  {
    id: "d-dot4",
    type: "dotColumn",
    gx: 25,
    gy: 6,
    wc: 0.6,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 74,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { dots: 7 },
  },
  {
    id: "d-arc3",
    type: "arc",
    gx: 22,
    gy: 16,
    wc: 5,
    hc: 5,
    rot: 0,
    tone: "ink",
    in: 76,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { start: 250, sweep: 80 },
  },
  {
    id: "d-arc4",
    type: "arc",
    gx: 20,
    gy: 8,
    wc: 5,
    hc: 5,
    rot: 0,
    tone: "dim",
    in: 78,
    inDur: 5,
    out: 230,
    outDur: 20,
    opts: { start: 60, sweep: 90 },
  },
  {
    id: "d-circ2",
    type: "circleOutline",
    gx: 27,
    gy: 14,
    wc: 5,
    hc: 5,
    rot: 0,
    tone: "dim",
    in: 80,
    inDur: 5,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-circ3",
    type: "circleOutline",
    gx: 17,
    gy: 10,
    wc: 4,
    hc: 4,
    rot: 0,
    tone: "ink",
    in: 82,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-brk5",
    type: "cornerBracket",
    gx: 17,
    gy: 15,
    wc: 2,
    hc: 2,
    rot: 90,
    tone: "accent",
    in: 84,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-panel3",
    type: "squarePanel",
    gx: 21,
    gy: 19,
    wc: 3,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 86,
    inDur: 5,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-chev1",
    type: "chevron",
    gx: 24,
    gy: 10,
    wc: 1.5,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 88,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { pair: true },
  },
  {
    id: "d-chev2",
    type: "chevron",
    gx: 20,
    gy: 14,
    wc: 1.5,
    hc: 3,
    rot: 180,
    tone: "ink",
    in: 90,
    inDur: 5,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { pair: true },
  },

  // ── wave three, frames 110-140: the small detail marks ───────────────────
  {
    id: "d-dash1",
    type: "dash",
    gx: 15,
    gy: 7,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 110,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-dash2",
    type: "dash",
    gx: 29,
    gy: 8,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 111,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-dash3",
    type: "dash",
    gx: 17,
    gy: 17,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "dim",
    in: 112,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-dash4",
    type: "dash",
    gx: 31,
    gy: 16,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 114,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-dash5",
    type: "dash",
    gx: 23,
    gy: 5,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 115,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-dash6",
    type: "dash",
    gx: 13,
    gy: 14,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "dim",
    in: 116,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-dash7",
    type: "dash",
    gx: 25,
    gy: 19,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "accent",
    in: 118,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-chev3",
    type: "chevron",
    gx: 16,
    gy: 11,
    wc: 1,
    hc: 1.5,
    rot: 0,
    tone: "ink",
    in: 119,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-chev4",
    type: "chevron",
    gx: 28,
    gy: 13,
    wc: 1,
    hc: 1.5,
    rot: 180,
    tone: "ink",
    in: 120,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-chev5",
    type: "chevron",
    gx: 22,
    gy: 7,
    wc: 1,
    hc: 1.5,
    rot: 0,
    tone: "dim",
    in: 121,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-chev6",
    type: "chevron",
    gx: 24,
    gy: 16,
    wc: 1,
    hc: 1.5,
    rot: 0,
    tone: "ink",
    in: 122,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-chev7",
    type: "chevron",
    gx: 18,
    gy: 12,
    wc: 1,
    hc: 1.5,
    rot: 180,
    tone: "dim",
    in: 124,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-diag1",
    type: "diagonalPair",
    gx: 15,
    gy: 16,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 125,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-diag2",
    type: "diagonalPair",
    gx: 29,
    gy: 10,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 126,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-diag3",
    type: "diagonalPair",
    gx: 21,
    gy: 6,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 128,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-diag4",
    type: "diagonalPair",
    gx: 26,
    gy: 17,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 129,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-diag5",
    type: "diagonalPair",
    gx: 19,
    gy: 18,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 130,
    inDur: 4,
    out: 230,
    outDur: 20,
  },
  {
    id: "d-diag6",
    type: "diagonalPair",
    gx: 32,
    gy: 15,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 131,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
  },
  {
    id: "d-dot5",
    type: "dotColumn",
    gx: 23,
    gy: 14,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 132,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { dots: 6 },
  },
  {
    id: "d-dot6",
    type: "dotColumn",
    gx: 27,
    gy: 7,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "dim",
    in: 134,
    inDur: 4,
    out: 230,
    outDur: 20,
    opts: { dots: 6 },
  },
  {
    id: "d-dot7",
    type: "dotColumn",
    gx: 15,
    gy: 12,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 135,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { dots: 6 },
  },
  {
    id: "d-dot8",
    type: "dotColumn",
    gx: 32,
    gy: 12,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "accent",
    in: 136,
    inDur: 4,
    out: 230,
    outDur: 20,
    flicker: true,
    opts: { dots: 6 },
  },
];
