import type { MarkSpec } from "../types";

/**
 * V3 "print" — registration.
 *
 * The inversion changes the meaning: black marks on warm off-white stop
 * reading as a HUD and start reading as press registration. Corner brackets
 * become crop marks whose arms stop short of meeting, targets sit at the
 * middle of each margin, and a colour bar runs along the bottom.
 *
 * Positions are mirror-symmetric about the frame's centre column and centre
 * row. The centre is as empty as v1's, but the emptiness reads as a page.
 * Nothing rotates. Marks stagger in once over frames 20-120, hold to 250, and
 * stagger cleanly back out by 300.
 */
export const PRINT_FIELD: MarkSpec[] = [
  {
    id: "p-crop-tl",
    type: "cropMark",
    gx: 1,
    gy: 1,
    wc: 1.5,
    hc: 1.5,
    rot: 0,
    tone: "ink",
    in: 20,
    inDur: 5,
    out: 250,
    outDur: 5,
  },
  {
    id: "p-crop-tr",
    type: "cropMark",
    gx: 27,
    gy: 1,
    wc: 1.5,
    hc: 1.5,
    rot: 90,
    tone: "ink",
    in: 23,
    inDur: 5,
    out: 251,
    outDur: 5,
  },
  {
    id: "p-crop-br",
    type: "cropMark",
    gx: 27,
    gy: 14,
    wc: 1.5,
    hc: 1.5,
    rot: 180,
    tone: "ink",
    in: 26,
    inDur: 5,
    out: 253,
    outDur: 5,
  },
  {
    id: "p-crop-bl",
    type: "cropMark",
    gx: 1,
    gy: 14,
    wc: 1.5,
    hc: 1.5,
    rot: 270,
    tone: "ink",
    in: 29,
    inDur: 5,
    out: 254,
    outDur: 5,
  },
  {
    id: "p-reg-top",
    type: "registrationTarget",
    gx: 14,
    gy: 1,
    wc: 2,
    hc: 2,
    rot: 0,
    tone: "accent",
    in: 32,
    inDur: 5,
    out: 256,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-reg-bot",
    type: "registrationTarget",
    gx: 14,
    gy: 14,
    wc: 2,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 35,
    inDur: 5,
    out: 257,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-reg-left",
    type: "registrationTarget",
    gx: 1,
    gy: 7.5,
    wc: 2,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 38,
    inDur: 5,
    out: 258,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-reg-right",
    type: "registrationTarget",
    gx: 27,
    gy: 7.5,
    wc: 2,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 41,
    inDur: 5,
    out: 260,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-tick-tl",
    type: "tickRow",
    gx: 6,
    gy: 1,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 44,
    inDur: 5,
    out: 261,
    outDur: 5,
    flicker: true,
    opts: { ticks: 10 },
  },
  {
    id: "p-tick-tr",
    type: "tickRow",
    gx: 22,
    gy: 1,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 47,
    inDur: 5,
    out: 263,
    outDur: 5,
    flicker: true,
    opts: { ticks: 10 },
  },
  {
    id: "p-tick-bl",
    type: "tickRow",
    gx: 6,
    gy: 14,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 50,
    inDur: 5,
    out: 264,
    outDur: 5,
    flicker: true,
    opts: { ticks: 10 },
  },
  {
    id: "p-tick-br",
    type: "tickRow",
    gx: 22,
    gy: 14,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 53,
    inDur: 5,
    out: 265,
    outDur: 5,
    flicker: true,
    opts: { ticks: 10 },
  },
  {
    id: "p-dot-lt",
    type: "dotColumn",
    gx: 1,
    gy: 3,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "dim",
    in: 56,
    inDur: 5,
    out: 267,
    outDur: 5,
    opts: { dots: 7 },
  },
  {
    id: "p-dot-rt",
    type: "dotColumn",
    gx: 27,
    gy: 3,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "dim",
    in: 59,
    inDur: 5,
    out: 268,
    outDur: 5,
    opts: { dots: 7 },
  },
  {
    id: "p-dot-lb",
    type: "dotColumn",
    gx: 1,
    gy: 12,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "dim",
    in: 62,
    inDur: 5,
    out: 270,
    outDur: 5,
    opts: { dots: 7 },
  },
  {
    id: "p-dot-rb",
    type: "dotColumn",
    gx: 27,
    gy: 12,
    wc: 0.5,
    hc: 2,
    rot: 0,
    tone: "dim",
    in: 65,
    inDur: 5,
    out: 271,
    outDur: 5,
    opts: { dots: 7 },
  },
  {
    id: "p-chev-lt",
    type: "chevron",
    gx: 1,
    gy: 5,
    wc: 0.8,
    hc: 1.5,
    rot: 0,
    tone: "ink",
    in: 68,
    inDur: 5,
    out: 272,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-chev-rt",
    type: "chevron",
    gx: 27,
    gy: 5,
    wc: 0.8,
    hc: 1.5,
    rot: 180,
    tone: "ink",
    in: 71,
    inDur: 5,
    out: 274,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-chev-lb",
    type: "chevron",
    gx: 1,
    gy: 10,
    wc: 0.8,
    hc: 1.5,
    rot: 0,
    tone: "ink",
    in: 74,
    inDur: 5,
    out: 275,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-chev-rb",
    type: "chevron",
    gx: 27,
    gy: 10,
    wc: 0.8,
    hc: 1.5,
    rot: 180,
    tone: "ink",
    in: 77,
    inDur: 5,
    out: 277,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-dash-tl",
    type: "dash",
    gx: 10,
    gy: 1,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 80,
    inDur: 5,
    out: 278,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-dash-tr",
    type: "dash",
    gx: 18,
    gy: 1,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 83,
    inDur: 5,
    out: 279,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-dash-bl",
    type: "dash",
    gx: 10,
    gy: 14,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 86,
    inDur: 5,
    out: 281,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-dash-br",
    type: "dash",
    gx: 18,
    gy: 14,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 89,
    inDur: 5,
    out: 282,
    outDur: 5,
    flicker: true,
  },
  {
    id: "p-diag-tl",
    type: "diagonalPair",
    gx: 7,
    gy: 3,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 92,
    inDur: 5,
    out: 284,
    outDur: 5,
  },
  {
    id: "p-diag-tr",
    type: "diagonalPair",
    gx: 21,
    gy: 3,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 95,
    inDur: 5,
    out: 285,
    outDur: 5,
  },
  {
    id: "p-diag-bl",
    type: "diagonalPair",
    gx: 7,
    gy: 12,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 98,
    inDur: 5,
    out: 286,
    outDur: 5,
  },
  {
    id: "p-diag-br",
    type: "diagonalPair",
    gx: 21,
    gy: 12,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "dim",
    in: 101,
    inDur: 5,
    out: 288,
    outDur: 5,
  },
  {
    id: "p-x",
    type: "crossedX",
    gx: 4,
    gy: 4,
    wc: 3,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 104,
    inDur: 5,
    out: 289,
    outDur: 5,
  },
  {
    id: "p-circ-tr",
    type: "circleOutline",
    gx: 24,
    gy: 4,
    wc: 3,
    hc: 3,
    rot: 0,
    tone: "dim",
    in: 107,
    inDur: 5,
    out: 291,
    outDur: 5,
  },
  {
    id: "p-circ-bl",
    type: "circleOutline",
    gx: 4,
    gy: 11,
    wc: 3,
    hc: 3,
    rot: 0,
    tone: "dim",
    in: 110,
    inDur: 5,
    out: 292,
    outDur: 5,
  },
  {
    id: "p-panel",
    type: "squarePanel",
    gx: 24,
    gy: 11,
    wc: 3,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 113,
    inDur: 5,
    out: 293,
    outDur: 5,
  },
  {
    id: "p-bar",
    type: "colourBar",
    gx: 14,
    gy: 15,
    wc: 8,
    hc: 0.5,
    rot: 0,
    tone: "ink",
    in: 116,
    inDur: 5,
    out: 295,
    outDur: 5,
    flicker: true,
    opts: { swatches: 7, accentAt: 4 },
  },
];
