import type { MarkSpec } from "../types";

/**
 * V1 "sparse" — edge-weighted.
 *
 * Pure data: type, grid position, size in grid cells, rotation, tone and a
 * fade window per entry. Marks cluster on the frame's edges and corners and
 * leave the centre empty; the only thing in the middle third of the frame is
 * the crossed X, right of centre, and it is the only element that moves.
 *
 * Arrivals run from the upper-right corner outward in pairs, 5-6 frames apart,
 * across frames 25-90. Departures follow a different order entirely, and four
 * stragglers hold past frame 265.
 */
export const SPARSE_FIELD: MarkSpec[] = [
  // ── upper right ───────────────────────────────────────────────────────────
  {
    id: "brk-tr",
    type: "cornerBracket",
    gx: 26,
    gy: 1,
    wc: 2,
    hc: 2,
    rot: 90,
    tone: "ink",
    in: 25,
    inDur: 5,
    out: 283,
    outDur: 5,
    flicker: true,
  },
  {
    id: "arc-tr",
    type: "arc",
    gx: 27,
    gy: 4,
    wc: 4,
    hc: 4,
    rot: 0,
    tone: "dim",
    in: 25,
    inDur: 6,
    out: 271,
    outDur: 6,
    opts: { start: 90, sweep: 110 },
  },
  {
    id: "chev-tr",
    type: "chevron",
    gx: 24,
    gy: 2,
    wc: 1,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 31,
    inDur: 4,
    out: 216,
    outDur: 5,
    opts: { pair: true },
    flicker: true,
  },
  {
    id: "tick-tr",
    type: "tickRow",
    gx: 21,
    gy: 1,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 31,
    inDur: 5,
    out: 204,
    outDur: 4,
    opts: { ticks: 10 },
    flicker: true,
  },
  {
    id: "dot-r",
    type: "dotColumn",
    gx: 28,
    gy: 8,
    wc: 1,
    hc: 3,
    rot: 0,
    tone: "ink",
    in: 36,
    inDur: 5,
    out: 277,
    outDur: 5,
    opts: { columns: 2, dots: 8 },
    flicker: true,
  },
  {
    id: "dash-r",
    type: "dash",
    gx: 24,
    gy: 6,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 36,
    inDur: 4,
    out: 223,
    outDur: 4,
    flicker: true,
  },

  // ── the one moving element, right of centre ──────────────────────────────
  {
    id: "x-mid",
    type: "crossedX",
    gx: 20,
    gy: 8,
    wc: 4,
    hc: 4,
    rot: 0,
    tone: "ink",
    in: 42,
    inDur: 6,
    out: 289,
    outDur: 5,
    spin: 1,
  },

  // ── lower right ──────────────────────────────────────────────────────────
  {
    id: "dot-br",
    type: "dotColumn",
    gx: 27,
    gy: 11,
    wc: 0.5,
    hc: 2.5,
    rot: 0,
    tone: "dim",
    in: 42,
    inDur: 5,
    out: 243,
    outDur: 5,
    opts: { dots: 7 },
    flicker: true,
  },
  {
    id: "panel-br",
    type: "squarePanel",
    gx: 24,
    gy: 13,
    wc: 3,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 47,
    inDur: 6,
    out: 208,
    outDur: 6,
  },
  {
    id: "brk-br",
    type: "cornerBracket",
    gx: 26,
    gy: 14,
    wc: 2,
    hc: 2,
    rot: 180,
    tone: "ink",
    in: 47,
    inDur: 5,
    out: 254,
    outDur: 5,
    flicker: true,
  },
  {
    id: "diag-br",
    type: "diagonalPair",
    gx: 21,
    gy: 14,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 53,
    inDur: 4,
    out: 231,
    outDur: 4,
    flicker: true,
  },
  {
    id: "tick-b",
    type: "tickRow",
    gx: 17,
    gy: 15,
    wc: 3,
    hc: 0.4,
    rot: 0,
    tone: "dim",
    in: 53,
    inDur: 5,
    out: 262,
    outDur: 5,
    opts: { ticks: 10 },
  },

  // ── upper left ───────────────────────────────────────────────────────────
  {
    id: "tick-t",
    type: "tickRow",
    gx: 5,
    gy: 0,
    wc: 4,
    hc: 0.4,
    rot: 0,
    tone: "ink",
    in: 58,
    inDur: 5,
    out: 239,
    outDur: 5,
    opts: { ticks: 13 },
    flicker: true,
  },
  {
    id: "dash-tl",
    type: "dash",
    gx: 4,
    gy: 1,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "ink",
    in: 58,
    inDur: 4,
    out: 247,
    outDur: 4,
    flicker: true,
  },
  {
    id: "brk-tl",
    type: "cornerBracket",
    gx: 1,
    gy: 1,
    wc: 2,
    hc: 2,
    rot: 0,
    tone: "ink",
    in: 69,
    inDur: 5,
    out: 235,
    outDur: 5,
    flicker: true,
  },
  {
    id: "dot-l",
    type: "dotColumn",
    gx: 1,
    gy: 4,
    wc: 0.5,
    hc: 3,
    rot: 0,
    tone: "dim",
    in: 75,
    inDur: 5,
    out: 212,
    outDur: 5,
    opts: { dots: 8 },
    flicker: true,
  },

  // ── left edge and lower left ─────────────────────────────────────────────
  {
    id: "chev-l",
    type: "chevron",
    gx: 2,
    gy: 5,
    wc: 1,
    hc: 2,
    rot: 180,
    tone: "ink",
    in: 69,
    inDur: 4,
    out: 251,
    outDur: 5,
    flicker: true,
  },
  {
    id: "arc-l",
    type: "arc",
    gx: 0,
    gy: 9,
    wc: 5,
    hc: 5,
    rot: 0,
    tone: "dim",
    in: 75,
    inDur: 6,
    out: 227,
    outDur: 6,
    opts: { start: 280, sweep: 100 },
  },
  {
    id: "diag-l",
    type: "diagonalPair",
    gx: 5,
    gy: 11,
    wc: 1,
    hc: 1,
    rot: 0,
    tone: "ink",
    in: 64,
    inDur: 4,
    out: 258,
    outDur: 4,
    flicker: true,
  },
  {
    id: "dash-bl",
    type: "dash",
    gx: 8,
    gy: 15,
    wc: 1,
    hc: 0.2,
    rot: 0,
    tone: "dim",
    in: 64,
    inDur: 4,
    out: 265,
    outDur: 4,
    flicker: true,
  },
  {
    id: "circ-bl",
    type: "circleOutline",
    gx: 0,
    gy: 13,
    wc: 7,
    hc: 7,
    rot: 0,
    tone: "dim",
    in: 80,
    inDur: 6,
    out: 200,
    outDur: 6,
  },
  {
    id: "brk-bl",
    type: "cornerBracket",
    gx: 5,
    gy: 14,
    wc: 2,
    hc: 2,
    rot: 270,
    tone: "ink",
    in: 80,
    inDur: 5,
    out: 220,
    outDur: 5,
    flicker: true,
  },
];
